import PalPeg.Basic
import PalPeg.Existence
import PalPeg.EvenLength
import PalPeg.Axioms
import PalPeg.Words
import PalPeg.Chain
import PalPeg.Structure
import PalPeg.Groups
import PalPeg.GroupsLog
import PalPeg.GroupsLogBound
import PalPeg.Matching
import PalPeg.GSScan
import PalPeg.GSDecomp
import PalPeg.GSDecompL1
import PalPeg.GSDecompose2
import PalPeg.GSDecompose2Work
import PalPeg.PassSum
import PalPeg.PassSum2
import PalPeg.PassSum3
import PalPeg.PassSum4
import PalPeg.PassSum5
import PalPeg.PassSum6
import PalPeg.PassSum7
import PalPeg.PassSum8
import PalPeg.GSPreprocess
import PalPeg.GSPreprocessTapes
import PalPeg.GSRealTime
import PalPeg.GSVerifier
import PalPeg.Metered
import PalPeg.GSScanTapes
import PalPeg.GSVerifierTapes
import PalPeg.TextFeed
import PalPeg.VerifierFeed
import PalPeg.StageMatcherTapes
import PalPeg.StageTapes
import PalPeg.FullMachineTapes
import PalPeg.ClearAny
import PalPeg.ProgLang
import PalPeg.ProgLangLib
import PalPeg.GSScanProg
import PalPeg.InputCopy
import PalPeg.PatternTapes
import PalPeg.PatternTapesPair
import PalPeg.Prologue
import PalPeg.BorderJob
import PalPeg.BorderJobTapes
import PalPeg.MiddleTapes
import PalPeg.RTQueue
import PalPeg.RTQueueTapes
import PalPeg.Manacher
import PalPeg.ManacherHeads
import PalPeg.MiddleJob
import PalPeg.Stages
import PalPeg.Assembly
import PalPeg.StageMatcher
import PalPeg.OnlineMachine
import PalPeg.MiddleBorder
import PalPeg.PrepDecompose
import PalPeg.EndToEnd
import PalPeg.EndToEnd2
import PalPeg.Schedule
import PalPeg.TapeLib
import PalPeg.Speedup
import PalPeg.ProgramMachine
import PalPeg.Main
import PalPeg.PointwiseGap
import PalPeg.StageTapesZ
import PalPeg.GSVerifierProgZ
import PalPeg.VerifierFeedZ
import PalPeg.GSVerifierTapesZ
import PalPeg.GSVerifierZ
import PalPeg.InputEmbed
import PalPeg.PassSumGen
import PalPeg.PassSum11
import PalPeg.Consumption
import PalPeg.DecompUniform
import PalPeg.MeteredX
import PalPeg.VerifierFeedX
import PalPeg.StageTapesX
import PalPeg.StageMatcherTapesX
import PalPeg.GSPreprocessProg3
import PalPeg.GSPreprocessProg4
import PalPeg.GSPreprocessProg5
import PalPeg.GSPreprocessProg6
import PalPeg.GSPreprocessProg7
import PalPeg.GSPreprocessProg8
import PalPeg.GSPreprocessProg9
import PalPeg.GSPreprocessProg10
import PalPeg.GSPreprocessProg11
import PalPeg.GSPreprocessProg12
import PalPeg.GSPreprocessProg13
import PalPeg.GSPreprocessProg14
import PalPeg.GSPreprocessProg15
import PalPeg.GSPreprocessProg16
import PalPeg.GSPreprocessProg17
import PalPeg.GSPreprocessProg18
import PalPeg.GSPreprocessProg19
import PalPeg.GSPreprocessProg20
import PalPeg.GSPreprocessProg21
import PalPeg.GSPreprocessProg22
import PalPeg.GSPreprocessProg23
import PalPeg.GSPreprocessProg24
import PalPeg.GSPreprocessProg25
import PalPeg.GSPreprocessProg26
import PalPeg.GSPreprocessProg27
import PalPeg.GSPreprocessProg28
import PalPeg.GSPreprocessProg29
import PalPeg.GSPreprocessProg30
import PalPeg.GSPreprocessProg31
import PalPeg.GSPreprocessProg32
import PalPeg.GSPreprocessProg33
import PalPeg.GSPreprocessProg34
import PalPeg.GSPreprocessProg35
import PalPeg.GSPreprocessProg36
import PalPeg.GSPreprocessProg37
import PalPeg.GSPreprocessProg38
import PalPeg.GSPreprocessProg39
import PalPeg.GSPreprocessProg40
import PalPeg.GSPreprocessProg41
import PalPeg.GSPreprocessProg42
import PalPeg.GSPreprocessProg43
import PalPeg.GSPreprocessProg44
import PalPeg.GSPreprocessProg45
import PalPeg.GSPreprocessProg46
import PalPeg.GSPreprocessProg47
import PalPeg.GSPreprocessProg48
import PalPeg.GSPreprocessProg49
import PalPeg.GSPreprocessProg50
import PalPeg.GSPreprocessProg51
import PalPeg.GSPreprocessProg52
import PalPeg.GSPreprocessProg53
import PalPeg.GSPreprocessProg54
import PalPeg.GSPreprocessProg55
import PalPeg.GSPreprocessProg56
import PalPeg.GSPreprocessProg57
import PalPeg.GSPreprocessProg58
import PalPeg.GSPreprocessProg59
import PalPeg.GSPreprocessProg60
import PalPeg.GSPreprocessProg61
import PalPeg.GSPreprocessProg62
import PalPeg.GSPreprocessProg63
import PalPeg.GSPreprocessProg64
import PalPeg.GSPreprocessProg65
import PalPeg.GSPreprocessProg66
import PalPeg.GSPreprocessProg67
import PalPeg.GSPreprocessProg68
import PalPeg.GSPreprocessProg69
import PalPeg.GSPreprocessProg70
import PalPeg.GSPreprocessProg71
import PalPeg.GSPreprocessProg72
import PalPeg.GSPreprocessProg73
import PalPeg.GSPreprocessProg74
import PalPeg.GSPreprocessProg75
import PalPeg.GSPreprocessProg76
import PalPeg.GSPreprocessProg2
import PalPeg.GSPreprocessProg
import PalPeg.PassSumRelabel
import PalPeg.InputCopySentinel
import PalPeg.PatternPairProg
import PalPeg.StageMatcherProg
import PalPeg.GSVerifierProgX
import PalPeg.TextFeedProg2
import PalPeg.TextFeedProg
import PalPeg.ProgLangPersist2
import PalPeg.ProgLangBank
import PalPeg.ProgLangBankTapes
import PalPeg.FinitePrepBank
import PalPeg.GSVerifierProgZLoop
import PalPeg.FiniteMatcherBank
import PalPeg.RTQueueDispatch
import PalPeg.RTQueueControl
import PalPeg.RTQueueDequeue
import PalPeg.RTQueueClosed
import PalPeg.TextFeedControl
import PalPeg.TextFeedTiming
import PalPeg.TextFeedInput
import PalPeg.RTQueueSlots
import PalPeg.RTQueueCalls
import PalPeg.ProgLangCallFrame
import PalPeg.TextFeedSchedule
import PalPeg.TextFeedScan
import PalPeg.TextFeedRefine
import PalPeg.TextFeedWork
import PalPeg.TextFeedDeadline
import PalPeg.TextFeedPhysicalDeadline
import PalPeg.TextFeedStream
import PalPeg.RTQueueInit
import PalPeg.TextFeedInit
import PalPeg.TextFeedPrepare
import PalPeg.ProgramBlankEq
import PalPeg.ProgLangBlankEq
import PalPeg.TextFeedUnpadded
import PalPeg.TextFeedMachine27
import PalPeg.TextFeedStartup
import PalPeg.TextFeedStartupBank
import PalPeg.TextFeedStartupSchedule
import PalPeg.TextFeedStartupSafety
import PalPeg.TextFeedStartupRun
import PalPeg.TextFeedPrepResume
import PalPeg.TextFeedPrepInterrupt
import PalPeg.TextFeedPrepFrames
import PalPeg.TextFeedPrepHandoff
import PalPeg.TextFeedWorkerBridge
import PalPeg.TextFeedBacklog
import PalPeg.TextFeedStartupBudget
import PalPeg.TextFeedPrepBootstrap
import PalPeg.TextFeedPrepStartupFrames
import PalPeg.TextFeedPrepFinish
import PalPeg.TextFeedPrepEndpoint
import PalPeg.TextFeedStartupUnpadded
import PalPeg.TextFeedPrepared
import PalPeg.TextFeedOffset
import PalPeg.TextFeedOffsetStream
import PalPeg.TextFeedWorkerArrival
import PalPeg.TextFeedWorkerStream
import PalPeg.TextFeedWarmBoundary
import PalPeg.TextFeedStartupClock
import PalPeg.TextFeedStartupBoundary
import PalPeg.TextFeedStageStartup
import PalPeg.TextFeedStageUnpadded
import PalPeg.TextFeedStageDeadline
import PalPeg.VerifierFeedClosed
import PalPeg.VerifierFeedShared
import PalPeg.VerifierFeedPrimitive
import PalPeg.VerifierFeedMachine
import PalPeg.VerifierFeedCompare
import PalPeg.DualQueue
import PalPeg.DualQueueInput
import PalPeg.DualQueueMachine
import PalPeg.DualQueueShared
import PalPeg.TextFeedAlign
import PalPeg.TextFeedPrefixControl
import PalPeg.TextFeedPrefixReady
import PalPeg.TextFeedPrefixAtomic
import PalPeg.TextFeedPrefixBank
import PalPeg.TextFeedPrefixMachine
import PalPeg.TextFeedPrefixCycle
import PalPeg.TextFeedPrefixFinish
import PalPeg.TextFeedPrefixRank
import PalPeg.TextFeedPrefixDeadline
import PalPeg.TextFeedPrefixVerifier
import PalPeg.TextFeedPipelineBank
import PalPeg.TextFeedPipelineControl
import PalPeg.TextFeedPipelineHandoff
import PalPeg.TextFeedPipelineFeedSource
import PalPeg.TextFeedPipelineArrival
import PalPeg.TextFeedPipelineVerifier
import PalPeg.TextFeedPipelineFeed2
import PalPeg.TextFeedPipelineFeed1Model
import PalPeg.TextFeedPipelineFeed1
import PalPeg.TextFeedPipelineFeedBody
import PalPeg.VerifierFeedRaw
import PalPeg.VerifierFeedRawPrimitive
import PalPeg.VerifierFeedRefinement
import PalPeg.TextFeedPipelineRaw
import PalPeg.TextFeedPipelineRefinement
import PalPeg.ProgLangGuarded
import PalPeg.TextFeedPipelineGuarded
import PalPeg.TextFeedPipelineKeep
import PalPeg.TextFeedPipelineSourceSafety
import PalPeg.TextFeedPipelineBranch
import PalPeg.TextFeedPipelineActionWait
import PalPeg.TextFeedPipelineObservations
import PalPeg.TextFeedPipelineInputObservations
import PalPeg.TextFeedPipelineFrames
import PalPeg.TextFeedPipelineGuardAgreement
import PalPeg.TextFeedPipelineFrameSafety
import PalPeg.TextFeedPipelineFrameInstruction
import PalPeg.TextFeedPipelineFrameFeeds
import PalPeg.TextFeedPipelineFrameControl
import PalPeg.TextFeedPipelineCoupled
import PalPeg.TextFeedPipelineIdealEngine
import PalPeg.TextFeedPipelineMacroResult
import PalPeg.TextFeedPipelineMacroBoundary
import PalPeg.TextFeedPipelineInputRun
import PalPeg.TextFeedPipelineMacroFit
import PalPeg.TextFeedPipelineInputMacro
import PalPeg.TextFeedPipelineFrameCost
import PalPeg.TextFeedPipelineInstructionCost
import PalPeg.VerifierFeedSupplyProgress
import PalPeg.TextFeedPipelineSupplyCost
import PalPeg.ProgLangDemand
import PalPeg.TextFeedPipelineDemand
import PalPeg.GSVerifierDemand
import PalPeg.GSVerifierDemandZ
import PalPeg.TextFeedPipelineMacroDemand
import PalPeg.TextFeedPipelineInputCredit
import PalPeg.TextFeedPipelineResumeCredit
import PalPeg.TextFeedPipelineReentry
import PalPeg.TextFeedPipelineReentryInput
import PalPeg.ProgLangHeadMoves
import PalPeg.GSVerifierHeadMoves
import PalPeg.TextFeedPipelineFrontier
import PalPeg.TextFeedPipelineReport
import PalPeg.TextFeedPipelineOutput
import PalPeg.TextFeedPipelineService
import PalPeg.TextFeedPipelineDeadline
import PalPeg.TextFeedPipelineObserved
import PalPeg.TextFeedPipelineOutputSound
import PalPeg.TextFeedPipelineInitial
import PalPeg.TextFeedPipelineOutputPrep
import PalPeg.TextFeedPipelineOutputPrepFinish
import PalPeg.TextFeedPipelineOutputPrefix
import PalPeg.TextFeedPipelineOutputPrefixFrames
import PalPeg.TextFeedPipelineOutputPrefixSetup
import PalPeg.TextFeedPipelineOutputInitial
import PalPeg.TextFeedPipelineOutputClock
import PalPeg.TextFeedPipelineOutputBudget
import PalPeg.TextFeedPipelineOutputBirth
import PalPeg.TextFeedPipelineOutputBoot
import PalPeg.TextFeedPipelineOutputTrace
import PalPeg.TextFeedPipelineOutputResume
import PalPeg.TextFeedPipelineParameters
import PalPeg.TextFeedPipelineStage
import PalPeg.TextFeedPipelineSlots
import PalPeg.SlotClock
import PalPeg.SlotClockSweep
import PalPeg.SlotClockGeneration
import PalPeg.SlotClockStartup
import PalPeg.SlotClockPosition
import PalPeg.SlotClockTime
import PalPeg.SlotClockEvents
import PalPeg.ProgramRecycle
import PalPeg.ProgramRecycleWindow
import PalPeg.ClockRecycleMachine
import PalPeg.ClockRecycleTrace
import PalPeg.HistoryConcat
import PalPeg.HistoryArrival
import PalPeg.HistoryRewind
import PalPeg.HistoryErase
import PalPeg.HistoryRecover
import PalPeg.HistoryReady
import PalPeg.ProgramArrivalLog
import PalPeg.HistoryReadyInput
import PalPeg.HistoryFreeze
import PalPeg.ProgramTapeRename
import PalPeg.HistoryRotation
import PalPeg.HistoryNext
import PalPeg.HistoryNextInput
import PalPeg.HistoryLoop
import PalPeg.SlotClockBirth
import PalPeg.ClockHistory
import PalPeg.ProgramWarmStart
import PalPeg.ClockHistoryStartup
import PalPeg.ClockHistoryPeriods
import PalPeg.ClockHistoryInvariant
import PalPeg.TextFeedPipelineBirthSource
import PalPeg.TextFeedPipelineBirthRestore
import PalPeg.TextFeedPipelineBirthCycle
import PalPeg.TextFeedPipelineBirthInputCycle
import PalPeg.TextFeedPipelineBacklog
import PalPeg.ProgramTapeReplay
import PalPeg.ProgramReplayArrival
import PalPeg.ReplayBufferTurn
import PalPeg.ReplayLoop
import PalPeg.ReplayLoopReplay
import PalPeg.ReplayLoopCapture
import PalPeg.ReplayLoopRecovery
import PalPeg.ReplayLoopRotation
import PalPeg.ReplayLoopEvents
import PalPeg.ReplayLoopEventCut
import PalPeg.ReplayLoopEventPadding
import PalPeg.ReplayArrivalRate
import PalPeg.ReplayContraction
import PalPeg.ReplayCyclePadded
import PalPeg.ReplayPaddedHandoff
import PalPeg.ReplayDrain
import PalPeg.GalilFifoDeadline
import PalPeg.GalilSourceCost
import PalPeg.GalilFppGraph
import PalPeg.GalilFppTrace
import PalPeg.GalilFppInstruction
import PalPeg.GalilFppCode
import PalPeg.GalilFppExecution
import PalPeg.GalilFppInputScan
import PalPeg.GalilFppCandidate
import PalPeg.GalilFppPrefix
import PalPeg.GalilFppCopy
import PalPeg.GalilFppCopyInstances
import PalPeg.GalilFppDelta
import PalPeg.GalilFppMaterialize
import PalPeg.GalilFppEnqueue
import PalPeg.GalilFppCache
import PalPeg.GalilFppFrontier
import PalPeg.GalilFppWriteOnce
import PalPeg.GalilFppFailure
import PalPeg.GalilFppFallbackBits
import PalPeg.GalilFppFallbackLoop
import PalPeg.GalilFppDeltaTape
import PalPeg.GalilFppForward
import PalPeg.GalilFppReadInstances
import PalPeg.GalilFppLazyForward
import PalPeg.GalilFppSupply
import PalPeg.GalilFppCompare
import PalPeg.GalilFppRetry
import PalPeg.GalilFppInputWord
import PalPeg.GalilFppGeneration
import PalPeg.GalilFppChain
import PalPeg.GalilFppMarked
import PalPeg.GalilFppMarkTransform
import PalPeg.GalilFppMarkSimulation
import PalPeg.GalilFppPreparation
import PalPeg.GalilFppPrepareRewind
import PalPeg.GalilFppPrepareCells
import PalPeg.GalilFppPrepareInit
import PalPeg.GalilFppPrepareLayout
import PalPeg.GalilFppMarkedLayout
import PalPeg.GalilDpTransform
import PalPeg.GalilDpPrepared
import PalPeg.GalilDpSearch
import PalPeg.GalilDpAdvance
import PalPeg.GalilDpExhaustion
import PalPeg.GalilDpLoop
import PalPeg.GalilDpStart
import PalPeg.GalilDpCorrect
import PalPeg.GalilDpSuffix
import PalPeg.GalilScaffoldTape
import PalPeg.GalilScaffoldProgram
import PalPeg.GalilScaffoldControl
import PalPeg.LocalBuffers
import PalPeg.GalilScaffoldPreload
import PalPeg.GalilScaffoldLoad
import PalPeg.GalilScaffoldLoading
import PalPeg.GalilScaffoldCopy
import PalPeg.GalilScaffoldCounter
import PalPeg.GalilScaffoldPlace
import PalPeg.GalilScaffoldInputHead
import PalPeg.GalilScaffoldInputTrace
import PalPeg.GalilScaffoldHeap
import PalPeg.GalilScaffoldHeapTape
import PalPeg.GalilScaffoldHeapProgram
import PalPeg.GalilScaffoldMoveGuards
import PalPeg.GalilScaffoldWriteGuards
import PalPeg.GalilScaffoldRawTapes
import PalPeg.GalilScaffoldNextPc
import PalPeg.GalilScaffoldRawTick
import PalPeg.GalilScaffoldRawSchedule
import PalPeg.GalilScaffoldSearchFinish
import PalPeg.GalilScaffoldMatchClock
import PalPeg.GalilFppReadCost
import PalPeg.GalilFppSupplyCost
import PalPeg.GalilFppGenerationCost
import PalPeg.GalilFppMarkedCost
import PalPeg.GalilDpPreparedCost
import PalPeg.GalilDpCost
import PalPeg.GalilScaffoldDpCost
import PalPeg.GalilScaffoldSearchRun
import PalPeg.GalilScaffoldChainAnswer
import PalPeg.GalilScaffoldChainPeriod
import PalPeg.GalilScaffoldChainCredits
import PalPeg.GalilScaffoldChainReady
import PalPeg.GalilScaffoldChainConsume
import PalPeg.GalilScaffoldChainVerifier
import PalPeg.GalilScaffoldChainSweep
import PalPeg.GalilScaffoldChainVerifyRun
import PalPeg.GalilScaffoldChainCatch
import PalPeg.GalilScaffoldChainWatch
import PalPeg.GalilScaffoldChainLag
import PalPeg.GalilScaffoldChainWatchTrace
import PalPeg.GalilScaffoldChainPrediction
import PalPeg.GalilScaffoldChainRestart
import PalPeg.GalilScaffoldChainPalindrome
import PalPeg.GalilScaffoldChainMirror
import PalPeg.GalilScaffoldChainInputSupply
import PalPeg.GalilScaffoldChainReadOrigin
import PalPeg.GalilScaffoldChainFallback
import PalPeg.GalilScaffoldStructured
import PalPeg.GalilScaffoldController
import PalPeg.GalilScaffoldTop
import PalPeg.GalilScaffoldTopChainVM
import PalPeg.GalilScaffoldTopScan
import PalPeg.GalilScaffoldTopShift
import PalPeg.GalilScaffoldTopFallback
import PalPeg.GalilScaffoldTopFpp
import PalPeg.GalilFppQuantum
import PalPeg.GalilScaffoldTopMarks
import PalPeg.GalilScaffoldTopRewind
import PalPeg.GalilScaffoldTopLens
import PalPeg.GalilScaffoldTopVM
import PalPeg.GalilScaffoldTopMerge
import PalPeg.GalilScaffoldTopSteps
import PalPeg.GalilScaffoldTopSteps2
import PalPeg.GalilScaffoldTopSteps3
import PalPeg.GalilScaffoldTopFallbackChain
import PalPeg.GalilScaffoldTopRewindChain
import PalPeg.GalilScaffoldTopCopyChain
import PalPeg.GalilScaffoldTopReplay
import PalPeg.GalilScaffoldTopScanMerge
import PalPeg.GalilScaffoldTopShiftCycle
import PalPeg.GalilScaffoldTopFallbackCycle
import PalPeg.GalilScaffoldTopScanRun
import PalPeg.GalilScaffoldTopJointRun
import PalPeg.GalilScaffoldTopWatch
import PalPeg.GalilScaffoldTopBranches
import PalPeg.GalilScaffoldTopOutput
import PalPeg.GalilScaffoldTopSearch
import PalPeg.GalilScaffoldTopChain
import PalPeg.GalilScaffoldTopChainStart
import PalPeg.GalilScaffoldTopChainCredits
import PalPeg.GalilScaffoldTopChainEntry
import PalPeg.GalilScaffoldTopRestart
import PalPeg.GalilScaffoldTopFound
import PalPeg.GalilScaffoldTopGeneralRun
import PalPeg.GalilScaffoldTopGeneralEvents
import PalPeg.GalilScaffoldTopChainUnique
import PalPeg.GalilScaffoldTopPrep
import PalPeg.GalilScaffoldTopWatchRun
import PalPeg.GalilScaffoldTopWatchSupply
import PalPeg.GalilScaffoldTopWatchGuard
import PalPeg.GalilScaffoldTopGuards
import PalPeg.GalilScaffoldTopInvariant
import PalPeg.GalilScaffoldTopShiftRound
import PalPeg.GalilScaffoldTopInvStep
import PalPeg.GalilScaffoldTopOnly
import PalPeg.GalilScaffoldTopMatchedSeq
import PalPeg.GalilScaffoldTopScanSeg
import PalPeg.GalilScaffoldTopRoundS
import PalPeg.GalilScaffoldTopRounds
import PalPeg.GalilScaffoldTopRoundBreak
import PalPeg.GalilScaffoldTopFreshEntry
import PalPeg.GalilScaffoldTopWatchSeg
import PalPeg.GalilScaffoldTopFirstRound
import PalPeg.GalilScaffoldTopChainLife
import PalPeg.GalilScaffoldTopWatchSegE
import PalPeg.GalilScaffoldTopFoundLife
import PalPeg.GalilScaffoldTopSearchRun
import PalPeg.GalilScaffoldTopSearchStage
import PalPeg.GalilScaffoldTopStagePrefix
import PalPeg.GalilScaffoldTopFirstStage
import PalPeg.GalilScaffoldTopFirstStagePrefix
import PalPeg.GalilScaffoldTopSegmentFacts
import PalPeg.GalilScaffoldTopIdleFound
import PalPeg.GalilScaffoldTopCentre
import PalPeg.GalilScaffoldTopSegmentHeads
import PalPeg.GalilScaffoldTopRoundsCounters
import PalPeg.GalilScaffoldTopReadyFound
import PalPeg.GalilScaffoldTopLifeRestart
import PalPeg.GalilScaffoldTopFoundLoop
import PalPeg.GalilScaffoldTopFallbackS
import PalPeg.GalilScaffoldTopFallbackCycleS
import PalPeg.GalilScaffoldTopFallbackRestart
import PalPeg.GalilScaffoldTopFallbackFound
import PalPeg.GalilScaffoldTopInitRestart
import PalPeg.GalilScaffoldTopOutputSound
import PalPeg.GalilScaffoldTopOutputLife
import PalPeg.GalilScaffoldTopOutputTrace
import PalPeg.GalilScaffoldTopOutputRound
import PalPeg.GalilScaffoldTopOutputLifeAll
import PalPeg.GalilScaffoldTopFallbackAll
import PalPeg.GalilScaffoldTopFallbackRestartAll
import PalPeg.GalilScaffoldTopOutputInit
import PalPeg.GalilScaffoldTopOutputCycle
import PalPeg.GalilMoveLemma
import PalPeg.GalilPredictability
import PalPeg.GalilLiveCentre
import PalPeg.GalilSpanCounter
import PalPeg.GalilLiveCentreSeg
import PalPeg.GalilLiveCentreFallback
import PalPeg.GalilPeriodCentre
import PalPeg.GalilLiveCentreReplay
import PalPeg.GalilPeriodUnion
import PalPeg.GalilSegmentCount
import PalPeg.GalilCandidatePeriod
import PalPeg.GalilLiveCentreCycle
import PalPeg.GalilLiveCentreSegs
import PalPeg.GalilFallbackCost
import PalPeg.GalilMinimalPeriod
import PalPeg.GalilPeriodNext
import PalPeg.GalilReadOriginPeriod
import PalPeg.GalilCandidateWindow
import PalPeg.GalilOriginPeriod
import PalPeg.GalilNoBelowFirst
import PalPeg.GalilPrepLeast
import PalPeg.GalilReportComplete
import PalPeg.GalilBreakPeriod
import PalPeg.GalilBreakNoBelow
import PalPeg.GalilStructuredSkeleton
import PalPeg.GalilLiveCentreLife
import PalPeg.GalilLedgerObligations
import PalPeg.GalilLiveCentreCycle2
import PalPeg.GalilBranchInvariants
import PalPeg.GalilSearchContract
import PalPeg.GalilSharedFunctional
import PalPeg.GalilVMEncode
import PalPeg.GalilBranchInvariants2
import PalPeg.GalilSearchResult
import PalPeg.GalilSearchReadyInv
import PalPeg.GalilRunEntries
import PalPeg.GalilSearchWait
import PalPeg.GalilLedgerObligations2
import PalPeg.GalilTickFun
import PalPeg.GalilGoodLag
import PalPeg.GalilSearchContractStage
import PalPeg.GalilRestartStage
import PalPeg.GalilChainEncode
import PalPeg.GalilTickFun2
import PalPeg.GalilTickFun3
import PalPeg.GalilFppRunSupply
import PalPeg.GalilMainLoopMInv
import PalPeg.GalilShiftH
import PalPeg.GalilEndOfInput
import PalPeg.LocalCounter
import PalPeg.LocalMirror
import PalPeg.LocalRoles
import PalPeg.GalilChainReadyProgress
import PalPeg.GalilChainTickable
import PalPeg.GalilLastRadius
import PalPeg.LocalInputView
import PalPeg.GalilSegmentConstruct
import PalPeg.CloseoutWatchRound20
import PalPeg.CloseoutPackRun15
import PalPeg.CloseoutWatchRound19
import PalPeg.CloseoutPreload26
import PalPeg.CloseoutCoreEnc20
import PalPeg.CloseoutPackRun14
import PalPeg.CloseoutPackRun13
import PalPeg.CloseoutPreload25
import PalPeg.CloseoutPreload24
import PalPeg.CloseoutCoreEnc19
import PalPeg.CloseoutPackRun12
import PalPeg.CloseoutPreload23
import PalPeg.CloseoutPackRun11
import PalPeg.CloseoutCoreEnc18
import PalPeg.CloseoutPreload22
import PalPeg.CloseoutScanMargin4
import PalPeg.CloseoutPreload21
import PalPeg.CloseoutCoreEnc17
import PalPeg.CloseoutPreload20
import PalPeg.CloseoutPreload19
import PalPeg.CloseoutPreload18
import PalPeg.CloseoutWatchRound18
import PalPeg.CloseoutPreload17
import PalPeg.CloseoutCoreEnc16
import PalPeg.CloseoutPackRun10
import PalPeg.CloseoutPreload16
import PalPeg.CloseoutWatchRound17
import PalPeg.CloseoutCoreEnc15
import PalPeg.CloseoutPreload15
import PalPeg.CloseoutScanMargin3
import PalPeg.CloseoutWatchRound16
import PalPeg.CloseoutPackRun9
import PalPeg.CloseoutWatchRound15
import PalPeg.CloseoutPreload14
import PalPeg.CloseoutCoreEnc14
import PalPeg.CloseoutScanMargin2
import PalPeg.CloseoutPackRun8
import PalPeg.CloseoutPreload13
import PalPeg.CloseoutCoreEnc13
import PalPeg.CloseoutScanMargin
import PalPeg.CloseoutPackRun7
import PalPeg.CloseoutPreload12
import PalPeg.CloseoutWatchRound14
import PalPeg.CloseoutPreload11
import PalPeg.CloseoutCoreEnc12
import PalPeg.CloseoutPackRun6
import PalPeg.CloseoutWatchRound13
import PalPeg.CloseoutPreload10
import PalPeg.CloseoutWatchRound12
import PalPeg.CloseoutPreload9
import PalPeg.CloseoutCoreEnc11
import PalPeg.CloseoutWatchRound11
import PalPeg.CloseoutPreload8
import PalPeg.CloseoutWatchRound10
import PalPeg.CloseoutPackRun5
import PalPeg.CloseoutWatchRound9
import PalPeg.CloseoutPreload7
import PalPeg.CloseoutWatchRound8
import PalPeg.CloseoutPackRun4
import PalPeg.CloseoutPreload6
import PalPeg.CloseoutCoreEnc10
import PalPeg.CloseoutWatchRound7
import PalPeg.CloseoutPackRun3
import PalPeg.CloseoutPreload5
import PalPeg.CloseoutPackRun2
import PalPeg.CloseoutCoreEnc9
import PalPeg.CloseoutWatchRound5
import PalPeg.CloseoutPackRun
import PalPeg.CloseoutCoreEnc7
import PalPeg.CloseoutCoreEnc8
import PalPeg.CloseoutWatchRound6
import PalPeg.CloseoutOracleI2
import PalPeg.CloseoutWatchRound4
import PalPeg.CloseoutCoreEnc6
import PalPeg.CloseoutPreload4
import PalPeg.CloseoutOracleI
import PalPeg.CloseoutWatchRound3
import PalPeg.CloseoutCoreEnc5
import PalPeg.CloseoutLPack6
import PalPeg.CloseoutWatchRound2
import PalPeg.CloseoutPreload3
import PalPeg.CloseoutLPack5
import PalPeg.CloseoutCoreEnc4
import PalPeg.CloseoutPreload2
import PalPeg.CloseoutWatchRound
import PalPeg.CloseoutLPack4
import PalPeg.CloseoutPreload
import PalPeg.CloseoutCoreEnc3
import PalPeg.CloseoutLPack3
import PalPeg.CloseoutWatchRun
import PalPeg.CloseoutWatchPhase3
import PalPeg.CloseoutRunEntriesS
import PalPeg.CloseoutCoreEnc2
import PalPeg.CloseoutWatchPhase2
import PalPeg.CloseoutLaterEntry
import PalPeg.CloseoutReadyStage
import PalPeg.CloseoutLPack2
import PalPeg.CloseoutLaterQuantum
import PalPeg.CloseoutRightBounds
import PalPeg.CloseoutLPack
import PalPeg.CloseoutCoreAgree
import PalPeg.CloseoutCoreEnc
import PalPeg.CloseoutPrepInputs3
import PalPeg.CloseoutWatchPhase
import PalPeg.CloseoutDebtAudit
import PalPeg.CloseoutCoreStep
import PalPeg.CloseoutFoundRoutes
import PalPeg.CloseoutRadPack4
import PalPeg.CloseoutPrepInputs2
import PalPeg.CloseoutFoundExits
import PalPeg.CloseoutPrepInputs
import PalPeg.CloseoutRadPack3
import PalPeg.CloseoutRunEntriesPaced
import PalPeg.CloseoutFoundBackground
import PalPeg.CloseoutFoundCompare
import PalPeg.CloseoutFoundReplay
import PalPeg.CloseoutRadPack2
import PalPeg.CloseoutContracts
import PalPeg.CloseoutRadPack
import PalPeg.CloseoutReportCase
import PalPeg.CloseoutReadinessAudit
import PalPeg.CloseoutFairWitness
import PalPeg.CloseoutCoreAudit
import PalPeg.GalilReadyFuelUses
import PalPeg.LocalWF
import PalPeg.GalilTrailRad
import PalPeg.GalilTickFair
import PalPeg.GalilSegmentConstructB
import PalPeg.GalilLeafStartShape
import PalPeg.GalilOracleMC4
import PalPeg.GalilLeafFb
import PalPeg.GalilLeafDp
import PalPeg.GalilInvPlus3
import PalPeg.GalilLeafPos
import PalPeg.GalilLeafReport
import PalPeg.GalilLeafPres
import PalPeg.GalilOracleMC3
import PalPeg.GalilTrailAssembly
import PalPeg.GalilTrailOrder
import PalPeg.GalilTrailSane
import PalPeg.GalilTickDet
import PalPeg.GalilLeafEnds
import PalPeg.GalilLeafMismatch
import PalPeg.GalilFinalAssembly4
import PalPeg.GalilLeafOutReplay
import PalPeg.GalilTrailFront
import PalPeg.GalilLeafQuiet
import PalPeg.LocalRealizesPhase
import PalPeg.GalilOracleLeaves2
import PalPeg.LocalRealizesScan
import PalPeg.GalilFoundStageInv
import PalPeg.GalilTrailBudget
import PalPeg.GalilOracleMC2
import PalPeg.GalilTrailChain
import PalPeg.GalilTrailScan
import PalPeg.LocalSysConcrete
import PalPeg.GalilNoShiftDischarge
import PalPeg.GalilFoundStage
import PalPeg.GalilReplayBudgetProof
import PalPeg.GalilInvPlus2
import PalPeg.GalilTrailProof
import PalPeg.LocalLedgerShift
import PalPeg.LocalLatchRealize
import PalPeg.GalilReplaySpan
import PalPeg.LocalTrackingLatch
import PalPeg.GalilChainCoupling
import PalPeg.GalilNoShiftStage
import PalPeg.GalilLookRefined
import PalPeg.GalilFinalAssembly3
import PalPeg.GalilLexMeasure
import PalPeg.GalilNeedBound
import PalPeg.GalilFoundLandingL
import PalPeg.GalilFinalAssembly2
import PalPeg.GalilLengthFloor
import PalPeg.GalilOracleMC
import PalPeg.GalilFinalBaseNeed
import PalPeg.GalilTruncTick
import PalPeg.GalilCentreLive
import PalPeg.GalilFinalAssembly
import PalPeg.GalilReplayGeneral2
import PalPeg.GalilCostedFound
import PalPeg.GalilThrottledRunGen
import PalPeg.GalilCostedFallback
import PalPeg.GalilInvPlus
import PalPeg.GalilLedgerThrottled
import PalPeg.LocalTick3
import PalPeg.GalilThrottledRun
import PalPeg.GalilLedgerAssembly2
import PalPeg.GalilFrontMono
import PalPeg.GalilWatchOkInst
import PalPeg.GalilTraceCost
import PalPeg.GalilPrepMatch
import PalPeg.GalilGlueBLeaves
import PalPeg.GalilArriveChain
import PalPeg.GalilOracleM
import PalPeg.GalilPlaceEvents
import PalPeg.GalilOneFallback
import PalPeg.GalilLaterRadius
import PalPeg.GalilCheckpoints
import PalPeg.GalilIntervalCost
import PalPeg.GalilTickArrive
import PalPeg.GalilRunTrace
import PalPeg.GalilReportPrefix
import PalPeg.LocalReplayParked
import PalPeg.GalilLedgerAssembly
import PalPeg.GalilLedgerQ64
import PalPeg.GalilLedgerCentres
import PalPeg.GalilLindley
import PalPeg.GalilReplayGeneral
import PalPeg.GalilBreakTerminal
import PalPeg.GalilEarlyBreak
import PalPeg.LocalReplaySwap
import PalPeg.GalilLatchTracking
import PalPeg.GalilCatchUpDistance
import PalPeg.LocalArrivalTiming
import PalPeg.GalilPrepClock
import PalPeg.GalilOracleLocal
import PalPeg.GalilFoundRadiusBound
import PalPeg.LocalTick1
import PalPeg.GalilOracleGlueC
import PalPeg.LocalChain
import PalPeg.GalilOracleGlueA
import PalPeg.LocalAlloc
import PalPeg.GalilChosenRadiusLe
import PalPeg.GalilOracleDischarge
import PalPeg.GalilOracleGlueB
import PalPeg.GalilReplayChainSeg
import PalPeg.GalilPrepTrace
import PalPeg.LocalArrival
import PalPeg.GalilCycleProgress
import PalPeg.GalilPrepConstruct
import PalPeg.GalilRunInv2
import PalPeg.GalilFoundLanding
import PalPeg.GalilRoundPeriod
import PalPeg.GalilReplaySegment
import PalPeg.GalilRealizeOfTracking
import PalPeg.GalilCycleFoundBackground
import PalPeg.GalilCycleGlue
import PalPeg.GalilReportReplay
import PalPeg.GalilReplayFound
import PalPeg.GalilRoundConstruct
import PalPeg.LocalState
import PalPeg.LocalTick2
import PalPeg.GalilBackgroundNotFound
import PalPeg.GalilReportReach
import PalPeg.LocalStepRealize
import PalPeg.GalilRadiusConsumed
import PalPeg.GalilLastLowerBreak
import PalPeg.GalilReplayRest
import PalPeg.GalilSegmentConstruct2
import PalPeg.GalilRoundsLeftmost
import PalPeg.GalilSegmentConstruct3
import PalPeg.GalilPeriodSpan
import PalPeg.GalilScaffoldTopProgressS
import PalPeg.GalilShortPeriod
import PalPeg.GalilLiveCentreMismatch
import PalPeg.GalilFallbackLanding
import PalPeg.GalilMidRoundFallback
import PalPeg.GalilRunInv
import PalPeg.GalilRunSkeleton
import PalPeg.GalilBootVM
import PalPeg.GalilWatchPhase
import PalPeg.GalilRewindSafe
import PalPeg.GalilLiveCentreShift
import PalPeg.GalilMismatchCaught
import PalPeg.GalilCycleNoShift
import PalPeg.GalilPreludeDone
import PalPeg.GalilPreludeEnds
import PalPeg.GalilScaffoldDouble
import PalPeg.GalilScaffoldWait
import PalPeg.GalilScaffoldWaitInterrupt
import PalPeg.GalilScaffoldTimingCost
import PalPeg.GalilScaffoldPrepareClock
import PalPeg.GalilScaffoldGrow
import PalPeg.GalilScaffoldAdvanceClock
import PalPeg.GalilScaffoldLower
import PalPeg.GalilScaffoldSourceReady
import PalPeg.GalilScaffoldPrepareControl
import PalPeg.GalilScaffoldStagePrepare
import PalPeg.GalilScaffoldPreparePaced
import PalPeg.GalilFrontier
import PalPeg.GalilShiftPack
import PalPeg.TextFeedPipelineReplay
import PalPeg.TextFeedPipelineRecycle
import PalPeg.TextFeedPipelineBirthBuild
import PalPeg.TextFeedPipelineBirthInput
import PalPeg.ProgLangCallFramePrefix
import PalPeg.TextFeedPipelinePrepWindow
import PalPeg.TextFeedPipelinePrepInput
import PalPeg.TextFeedPipelinePrepFrames
import PalPeg.TextFeedPipelinePrepFinish
import PalPeg.TextFeedPipelinePrepSetup
import PalPeg.TextFeedPipelinePrepReady
import PalPeg.TextFeedPipelinePrefixLink
import PalPeg.TextFeedPipelinePrefixWindow
import PalPeg.TextFeedPipelinePrefixStart
import PalPeg.TextFeedPipelinePrefixFrames
import PalPeg.TextFeedPipelinePrefixHit
import PalPeg.TextFeedPipelinePrefixPhysical
import PalPeg.TextFeedPipelinePrefixEndpoint
import PalPeg.TextFeedPipelinePrefixResume
import PalPeg.TextFeedPipelinePrefixPartial
import PalPeg.TextFeedPipelinePrefixPrepared
import PalPeg.TextFeedPipelinePrefixSetup
import PalPeg.TextFeedPipelinePrefixReserve
import PalPeg.TextFeedPipelinePrefixFedHit
import PalPeg.TextFeedPipelinePrefixFedPhysical
import PalPeg.TextFeedPipelinePrefixFedSetup
import PalPeg.ProgLangPersist
import PalPeg.LocalBudget
import PalPeg.LocalTracking
import PalPeg.GalilEmptyWord
import PalPeg.LocalSchedule

/-!
# PalPeg

回文言語 `PAL ⊆ {0,1}*` が PEG 言語であることを、Kim–Park の Lean 成果物
(`PegSeparation`) を経由して**条件付きで**証明する。

* `PalPeg.Basic`     — `PAL` の定義と反転不変性
* `PalPeg.Existence` — 厳密実時間 TM が `PAL` を認識するならば total PEG が `PAL` を認識する
* `PalPeg.EvenLength` — 偶数長への制限（Loff–Moreira–Reis Conjecture 7 の条件付き反駁）
* `PalPeg.Axioms`    — `#print axioms` の guard
* `PalPeg.Words`     — 回文と周期の組合せ論（拡張則・境界・Fine–Wilf・group 補題）
* `PalPeg.Structure` — レプリカ・境界・予測補題・禁止帯（`lsp_shift_bound`）と (M) の反例
* `PalPeg.Groups`    — group 圧縮した鎖（2 回の記号参照/群）が `chain` を展開する
* `PalPeg.GroupsLog` — group 併合・正準性・境界縮小 `3ℓ' < 2ℓ`；`GroupsLogBound` で群数 ≤ 2·log₂|v|+4 を無条件化
* `PalPeg.Matching`  — KMP 一歩・境界鎖・Galil の予測補題（仕事 ≤ 保証ゼロ出力数）
* `PalPeg.Manacher`  — Manacher の radius 走査の正しさ、接頭辞回文フラグ、仕事量 ≤ n
* `PalPeg.ManacherHeads` — Manacher をテープ上で走らせたときのヘッド総移動 ≤ 7|x|（telescoping）
* `PalPeg.MiddleJob` — 中央回文フラグ：区切り埋め込みで偶奇統一、4 分割ジョブの費用 ≤ 128h と締切 `middle_flag_spec`
* `PalPeg.Stages`    — dyadic stage 分解 `Pal(n) ⇔ match_W ∧ middle_W`、段の被覆と同時稼働 ≤ 2
* `PalPeg.Assembly`  — 段の組み立て：照合/中央オラクル ⇒ `answer_correct`、`answer_length_iff_mem_PAL`、生成/退役/オンライン性
* `PalPeg.StageMatcher` — GS 照合器が `MatchOracle` を満たす（`dyadic_gs_mem_PAL`、オンライン性 `answer_take`）
* `PalPeg.OnlineMachine` — 全体機械の添字モデル（2 段、中央/前処理はインターフェース）`output_correctH`（半分割：段 S はパターン rev(w.take(S/2))、前処理 (S/2,S]、テキスト w.drop S）、ラウンド費用 ≤ 3(3(k+1)+Cm+Cp)
* `PalPeg.MiddleBorder` — 境界列挙版の `MiddleImpl`、`MiddleImplSpecH` を Cm=27901 で満たす（各段 L1 を仮定）
* `PalPeg.PrepDecompose` — `decompose` を (S/2,S] に均す `PrepImpl`、`PrepImplSpecH`（`decompose` の L1 を仮定）
* `PalPeg.EndToEnd`  — 添字レベルの端到端：`endToEnd_mem_PAL`（仮定は `decompose` の L1 のみ）、ラウンド費用 ≤ 84846
* `PalPeg.EndToEnd2` — `decompose2` 版の端到端：仮定は `PassPeriodSum 8 C₁`（1 パスの周期和 ≤ C₁T）のみ
* `PalPeg.Schedule`  — 順序処理の締切（`finishTime_le`）と Galil の FIFO サービス不等式（Lindley）
* `PalPeg.TapeLib`   — 成果物のテープ上の zipper / stack / seq / counter ビューと 1 アクション補題
* `PalPeg.GSScan`    — Galil–Seiferas 走査：安全シフト、健全性/完全性、ポテンシャル `Φ=(k+1)pos+q`
* `PalPeg.GSDecomp`  — GS 分解 `GSCore/GSDecomp`、k 反復周期の補題、走査側帰結と `KSimple` への橋；`GSDecompL1` で真の L1 境界 `gsDecomp_exists`（パスは p₂ 手前で停止）
* `PalPeg.Speedup`   — 1 記号あたり B マイクロステップの機械 → 厳密実時間 `Machine`（線形加速、`multiStep_recognizedBy`）
* `PalPeg.GSRealTime` — GS 走査の実時間実行：レート k+1 で `online_answer_correct`、有界遅れ不変量 `onlineRun_phi`、u 検証器の締切
* `PalPeg.GSVerifier` — u 検証器を quota 2 で交互実行（オラクルなし `vAnswer_correct`、1 ラウンド ≤ 3(k+1)）
* `PalPeg.ProgramMachine` — 構造化機械 `StructuredMachine`（有限型の制御・記号）→ `MultiStepMachine` → `RecognizedBy`、phase 記法
* `PalPeg.GSScanTapes` — GS 走査 1 歩を 3 テープ（P/Txt/Cnt）の動作列で実現、コスト ≤ (2k+2)ΔΦ+8
* `PalPeg.GSVerifierTapes` — u 検証器の 5 テープ化、走行費用 ≤ (2k+3)ΔΦ+18n（L1 不要で償却）
* `PalPeg.TextFeed`   — 到着記号を FIFO で走査テープに供給、`feed_online` で `onlineRun` を再現
* `PalPeg.InputCopy` — 入力コピー（フロンティア書き込み 1 動作/ラウンド、左読み）
* `PalPeg.PatternTapesPair` — 凍結された入力対（`tIn`, `tF`）からのセットアップ（13 テープ、`setup_spec_pair` ≤ 7(h+kp₁+1)、`copyPairToSingle`）
* `PalPeg.PatternTapes` — 段のセットアップ（入力コピーからパターン/U/カウンタ群を構築、≤ 21h 動作）
* `PalPeg.BorderJob`  — 中央フラグの GS 系境界列挙（縮小段、`palPrefixFlagsGS_spec`、仕事 ≤ 258|x|）
* `PalPeg.RTQueueTapes` — Hood–Melville キューを 9 本のスタックテープで実現（snoc ≤ 20、tail ≤ 27 動作；`lenr ≤ lenf` 判定は仮定）
* `PalPeg.GSPreprocess` — 計算可能な GS 分解 `decompose`（Python と一致）、`decompose_spec : GSCore`、1 パス線形（全体は L1 待ち）
* `PalPeg.Main`      — `pal_in_peg_of_structured`：PAL を SAccepts する構造化機械があれば `RecognizedByTotalPEG PAL`
* `PalPeg.BorderJobTapes` — 境界列挙の 6 テープ化、テープ仕事 ≤ 4000|x|、`flags_on_tape`
* `PalPeg.GSDecompose2` — 失敗位置へジャンプする strip 規則の `decompose2`：`decompose2_gsDecomp`（L1 無条件）
* `PalPeg.VerifierFeed` — 検証器の Txt2 も FIFO で供給（`.X .right` ごとの fill 版を続行中）
* `PalPeg.MiddleTapes` — 中央ジョブのバッチをテープ上で実行（`batch_read_flag`、レート `rateM`；ラウンド組み立ては続行中）
* `PalPeg.GSPreprocessTapes` — 前処理のテープ化（firstPeriod/extendReach/secondOuter、1 反復 ≤ (2k+65)·work+k+3；strip2 続行中）
* `PalPeg.GSDecompose2Work` — `decompose2` の仕事量：Σp_j ≤ C₁T を仮定すれば線形（仮定の真偽を検証中）
* `PalPeg.Metered`   — 固定 B 動作/ラウンドの de-amortization（`metered_phi`、境界で `metered_answer_correct`）
* `PalPeg.PassSum`   — 1 パスの連続 run start の二分律（(k−1) 倍で減るか増える）、領域端の単調性；`Σp_j ≤ C₁T` は未証明
* `PalPeg.StageMatcherTapes` — 段の照合フェーズ：固定 `roundBudget = 85 + U·B` 動作/ラウンド、`stage_answer_stageMatchH`
* `PalPeg.StageTapes` — 段のライフサイクル（前処理→セットアップ→照合＋中央）を 1 ラウンド ≤ `Cstage` 動作で実行、`stage_tapes_spec`
* `PalPeg.FullMachineTapes` — 全体機械（4 スロット回転、常駐 ≤3 段、分散クリア）、`full_answer_mem_PAL`（段インターフェース前提）
* `PalPeg.ClearAny` — 任意形状のテープの消去（`clearAny` ≤ 3·幅+3、`width_runProg`、チャンク分割）
* `PalPeg.ProgLang` — 有限制御プログラム言語（`Prog`、`while c do {act; body}`）と `StructuredMachine` への橋（`progMachine_round`、`progMachine_recognizedBy`）
* `PalPeg.ProgLangLib` — 移植用ライブラリ（`Exec`、単テープ動作→ベクトル `touchVec`）
* `PalPeg.GSScanProg` — GS 走査器 `program'` の ProgLang 移植（`scanProg_trace`：トレース＝動作リスト、追加マイクロステップ 0）
* `PalPeg.RTQueue`   — Hood–Melville 実時間キューと FIFO 仕様
* `PalPeg.Chain`     — 接尾辞回文鎖のオンライン参照算法と `w ∈ PAL ↔ |w| ∈ chain w`
-/
