import PalPeg.CloseoutCoreEnc24

/-!
# Closeout, step 2y: the role table as a **finite tag**, not an existential

placeholder
-/

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace PalPeg.CloseoutCoreEnc25

open PalPeg
open PalPeg.CloseoutCoreStep (Γc blankc)
open PalPeg.CloseoutCoreEnc12 (Act actList)
open PalPeg.CloseoutCoreEnc20 (Delta dApply dActs dDebris dActs_length viewTapesQ viewTapesQ_delta
  qActs qDebris qActs_length rotStart)
open PalPeg.CloseoutCoreEnc21 (SRole SRoles SInj sinj_iff LaysS sRoleList ovrL toAddr toAddr_eq
  laysS_delta pushRearD tailD revD appStartD appD invalDoneD rotPerm donePerm rotRolesS doneRolesS
  SStep finish finish_steps)
open PalPeg.CloseoutCoreEnc22 (SBound)
open PalPeg.CloseoutCoreEnc23 (roleIdx sinj_roleIdx sbound_roleIdx)
open PalPeg.RTQueue (Queue RotationState)
open Relation (ReflTransGen)

/-! ## 0. `SRole` is a seven-element type -/

instance : Fintype SRole :=
  ⟨⟨[SRole.front, .rear, .fwd, .fwd', .rev, .rev', .shadow], by decide⟩,
    by intro x; cases x <;> decide⟩

/-! ## 1. The group generated by the two role permutations -/

/-- The finite tag the control has to carry: the number of rotation starts
`mod 4` and the number of installs `mod 2`. -/
abbrev RTag : Type := Fin 4 × Bool

/-- `rotPerm` iterated. -/
def rotPow : ℕ → SRole → SRole
  | 0, ro => ro
  | (n + 1), ro => rotPerm (rotPow n ro)

/-- The permutation a tag stands for: `rotPerm ^ i ∘ donePerm ^ j`. -/
def tagPerm (t : RTag) (ro : SRole) : SRole :=
  rotPow t.1.val (if t.2 then donePerm ro else ro)

def rotTag (t : RTag) : RTag := (t.1 + 1, t.2)

def doneTag (t : RTag) : RTag := (t.1, !t.2)

/-- **The role table determined by a tag.** -/
def roleOf (t : RTag) : SRoles := fun ro => roleIdx (tagPerm t ro)

theorem rotPerm_donePerm (ro : SRole) : rotPerm (donePerm ro) = donePerm (rotPerm ro) := by
  revert ro; decide

theorem rotPow_four (ro : SRole) : rotPow 4 ro = ro := by
  revert ro; decide

theorem donePerm_donePerm (ro : SRole) : donePerm (donePerm ro) = ro := by
  revert ro; decide

theorem tagPerm_rot (t : RTag) (ro : SRole) : tagPerm (rotTag t) ro = tagPerm t (rotPerm ro) := by
  revert t ro; decide

theorem tagPerm_done (t : RTag) (ro : SRole) :
    tagPerm (doneTag t) ro = tagPerm t (donePerm ro) := by
  revert t ro; decide

theorem roleOf_rotTag (t : RTag) : roleOf (rotTag t) = rotRolesS (roleOf t) := by
  funext ro; exact congrArg roleIdx (tagPerm_rot t ro)

theorem roleOf_doneTag (t : RTag) : roleOf (doneTag t) = doneRolesS (roleOf t) := by
  funext ro; exact congrArg roleIdx (tagPerm_done t ro)

theorem sinj_roleOf (t : RTag) : SInj (roleOf t) := by
  show ∀ a b : SRole, roleOf t a = roleOf t b → a = b
  revert t; decide

theorem sbound_roleOf (t : RTag) : SBound (roleOf t) := by
  show ∀ ro : SRole, roleOf t ro < 7
  revert t; decide

/-- **The eight tables are pairwise distinct**: the tag is not redundant data. -/
theorem roleOf_inj (t t' : RTag) (h : ∀ ro, roleOf t ro = roleOf t' ro) : t = t' := by
  revert t t'; decide

/-- The tag advances by `rotTag` then `doneTag` on each complete rotation, and
that composite has **order 4**: three rotations do not restore the table. -/
theorem tag_cycle (t : RTag) :
    doneTag (rotTag (doneTag (rotTag (doneTag (rotTag (doneTag (rotTag t))))))) = t := by
  revert t; decide

theorem tag_cycle_ne (t : RTag) : doneTag (rotTag t) ≠ t := by
  revert t; decide


/-! ## 2. The sub-step as a *function*: no existential table, no existential junk -/

/-- The six Hood–Melville sub-steps, as operations the control *selects*
(`CloseoutCoreEnc21.SStep` is the corresponding relation). -/
inductive SOp where
  | snocPush (a : Fin 2)
  | tailPop
  | inval
  | rotStart
  | exec
  | install
  deriving DecidableEq

def isIdle (s : RotationState (Fin 2)) : Bool :=
  match s with | .idle => true | _ => false

def isDone (s : RotationState (Fin 2)) : Bool :=
  match s with | .done _ => true | _ => false

theorem isIdle_eq {s : RotationState (Fin 2)} (h : isIdle s = true) : s = .idle := by
  cases s <;> simp [isIdle] at h ⊢

theorem isDone_eq {s : RotationState (Fin 2)} (h : isDone s = true) : ∃ f, s = .done f := by
  cases s <;> simp [isDone] at h ⊢
  exact ⟨_, rfl⟩

/-- The queue after the selected sub-step. -/
def sApply : SOp → Queue (Fin 2) → Queue (Fin 2)
  | .snocPush a, q => { q with lenr := q.lenr + 1, rear := a :: q.rear }
  | .tailPop, q => if q.front = [] then q else { q with lenf := q.lenf - 1, front := q.front.tail }
  | .inval, q => { q with state := RTQueue.invalidate q.state }
  | .rotStart, q => if isIdle q.state then rotStart q else q
  | .exec, q => { q with state := RTQueue.exec q.state }
  | .install, q => finish q

/-- **The tag update**: it reads the op and *two bits* of `q.state`. -/
def tagStep : SOp → Queue (Fin 2) → RTag → RTag
  | .rotStart, q, t => if isIdle q.state then rotTag t else t
  | .install, q, t => if isDone q.state then doneTag t else t
  | _, _, t => t

/-- **The tag update is a bounded read.** -/
theorem tagStep_two_bits (op : SOp) (q q' : Queue (Fin 2)) (t : RTag)
    (hi : isIdle q.state = isIdle q'.state) (hd : isDone q.state = isDone q'.state) :
    tagStep op q t = tagStep op q' t := by
  cases op <;> simp [tagStep, hi, hd]

/-! ### The role-indexed deltas, selected by the rotation state -/

def invalDelta (ρ : SRoles) : RotationState (Fin 2) → (ℕ → Delta)
  | .appending 0 _ (_ :: _) => toAddr ρ invalDoneD
  | _ => toAddr ρ (fun _ => .keep)

def execDelta (ρ : SRoles) : RotationState (Fin 2) → (ℕ → Delta)
  | .reversing _ (x :: _) _ (y :: _) _ => toAddr ρ (revD x y)
  | .reversing _ [] _ [y] _ => toAddr ρ (appStartD y)
  | .appending (_ + 1) (x :: _) _ => toAddr ρ (appD x)
  | _ => toAddr ρ (fun _ => .keep)

/-- The delta family the sub-step applies: a **function** of op, queue, table. -/
def deltaOf : SOp → Queue (Fin 2) → SRoles → (ℕ → Delta)
  | .snocPush a, _, ρ => toAddr ρ (pushRearD a)
  | .tailPop, q, ρ =>
      if q.front = [] then toAddr ρ (fun _ => .keep) else toAddr ρ (tailD (isIdle q.state))
  | .inval, q, ρ => invalDelta ρ q.state
  | .rotStart, _, ρ => toAddr ρ (fun _ => .keep)
  | .exec, q, ρ => execDelta ρ q.state
  | .install, _, ρ => toAddr ρ (fun _ => .keep)

def invalJunk (ρ : SRoles) (J : ℕ → List (Fin 2)) :
    RotationState (Fin 2) → (ℕ → List (Fin 2))
  | .appending 0 f' (_ :: _) => ovrL (ρ .fwd') (f' ++ J (ρ .fwd')) J
  | _ => J

def execJunk (ρ : SRoles) (J : ℕ → List (Fin 2)) :
    RotationState (Fin 2) → (ℕ → List (Fin 2))
  | .appending 0 f' _ => ovrL (ρ .fwd') (f' ++ J (ρ .fwd')) J
  | _ => J

/-- The new junk: a **function** of op, queue, table, old junk. -/
def junkOf : SOp → Queue (Fin 2) → SRoles → (ℕ → List (Fin 2)) → (ℕ → List (Fin 2))
  | .inval, q, ρ, J => invalJunk ρ J q.state
  | .exec, q, ρ, J => execJunk ρ J q.state
  | .install, q, ρ, J => if isDone q.state then ovrL (ρ .front) (q.front ++ J (ρ .front)) J else J
  | _, _, _, J => J

theorem toAddr_keep (ρ : SRoles) (i : ℕ) : toAddr ρ (fun _ => Delta.keep) i = .keep := by
  unfold toAddr
  split_ifs <;> rfl

theorem dApply_keep_fam (ρ : SRoles) (L : ℕ → List (Fin 2)) :
    (fun i => dApply (toAddr ρ (fun _ => Delta.keep) i) (L i)) = L := by
  funext i; rw [toAddr_keep]; rfl

/-- **Every sub-step is a chain of `SStep`s** (refl when the guard is off). -/
theorem sstep_sApply (op : SOp) (q : Queue (Fin 2)) : ReflTransGen SStep q (sApply op q) := by
  cases op with
  | snocPush a => exact ReflTransGen.single (SStep.snocPush q a)
  | tailPop =>
      show ReflTransGen SStep q (if q.front = [] then _ else _)
      by_cases hf : q.front = []
      · rw [if_pos hf]
      · rw [if_neg hf]
        obtain ⟨c, f, hcf⟩ : ∃ c f, q.front = c :: f := by
          cases hq : q.front with
          | nil => exact absurd hq hf
          | cons c f => exact ⟨c, f, rfl⟩
        rw [hcf]
        exact ReflTransGen.single (SStep.tailPop q c f hcf)
  | inval => exact ReflTransGen.single (SStep.inval q)
  | rotStart =>
      show ReflTransGen SStep q (if isIdle q.state then _ else _)
      by_cases hi : isIdle q.state = true
      · rw [if_pos hi]
        exact ReflTransGen.single (SStep.rotStart q (isIdle_eq hi))
      · rw [if_neg hi]
  | exec => exact ReflTransGen.single (SStep.exec q)
  | install => exact finish_steps q

/-- **The layout step, de-existentialised.**  Compare
`CloseoutCoreEnc21.sstep_lays`, whose new table and new junk are produced by an
`∃`: here the new table is `roleOf (tagStep op q t)` and the new junk
`junkOf op q (roleOf t) J`, both *functions* of the old data. -/
theorem laysS_sApply (op : SOp) (q : Queue (Fin 2)) (t : RTag) (L J : ℕ → List (Fin 2))
    (h : LaysS q (roleOf t) L J) :
    LaysS (sApply op q) (roleOf (tagStep op q t))
      (fun i => dApply (deltaOf op q (roleOf t) i) (L i)) (junkOf op q (roleOf t) J) := by
  have hinj : SInj (roleOf t) := sinj_roleOf t
  have hL : ∀ ro, L (roleOf t ro) = sRoleList q ro ++ J (roleOf t ro) := h
  cases op with
  | snocPush a =>
      refine laysS_delta hinj h (pushRearD a) ?_
      intro ro; cases ro <;> simp [pushRearD, dApply, sRoleList, sApply]
  | tailPop =>
      show LaysS (if q.front = [] then _ else _) (roleOf t)
        (fun i => dApply ((if q.front = [] then _ else _ : ℕ → Delta) i) (L i)) J
      by_cases hf : q.front = []
      · rw [if_pos hf, if_pos hf, dApply_keep_fam]; exact h
      · rw [if_neg hf, if_neg hf]
        refine laysS_delta hinj h (tailD (isIdle q.state)) ?_
        obtain ⟨c, f, hcf⟩ : ∃ c f, q.front = c :: f := by
          cases hq : q.front with
          | nil => exact absurd hq hf
          | cons c f => exact ⟨c, f, rfl⟩
        intro ro
        cases hst : q.state <;> cases ro <;>
          simp [tailD, dApply, sRoleList, hst, hcf, isIdle]
  | inval =>
      show LaysS { q with state := RTQueue.invalidate q.state } (roleOf t)
        (fun i => dApply (invalDelta (roleOf t) q.state i) (L i)) (invalJunk (roleOf t) J q.state)
      match hst : q.state with
      | .appending 0 f' (x :: r') =>
          rw [show invalDelta (roleOf t) q.state = toAddr (roleOf t) invalDoneD by rw [hst]; rfl,
            show invalJunk (roleOf t) J q.state
              = ovrL (roleOf t .fwd') (f' ++ J (roleOf t .fwd')) J by rw [hst]; rfl]
          refine laysS_delta hinj h invalDoneD ?_
          intro ro; cases ro <;>
            simp [invalDoneD, dApply, sRoleList, hst, RTQueue.invalidate, ovrL, sinj_iff hinj]
      | .appending 0 f' [] =>
          rw [show invalDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl,
            show invalJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.invalidate]
      | .appending (n + 1) f' r' =>
          rw [show invalDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl,
            show invalJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.invalidate]
      | .reversing ok f f' r r' =>
          rw [show invalDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl,
            show invalJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.invalidate]
      | .idle =>
          rw [show invalDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl,
            show invalJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.invalidate]
      | .done f0 =>
          rw [show invalDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl,
            show invalJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.invalidate]
  | rotStart =>
      show LaysS (if isIdle q.state then _ else _)
        (roleOf (if isIdle q.state then rotTag t else t))
        (fun i => dApply (toAddr (roleOf t) (fun _ => Delta.keep) i) (L i)) J
      rw [dApply_keep_fam]
      by_cases hi : isIdle q.state = true
      · rw [if_pos hi, if_pos hi, roleOf_rotTag]
        have hidle : q.state = .idle := isIdle_eq hi
        intro ro
        show L (rotRolesS (roleOf t) ro) = _
        cases ro <;> simp [rotRolesS, rotPerm, hL, sRoleList, rotStart, hidle]
      · rw [if_neg hi, if_neg hi]; exact h
  | exec =>
      show LaysS { q with state := RTQueue.exec q.state } (roleOf t)
        (fun i => dApply (execDelta (roleOf t) q.state i) (L i)) (execJunk (roleOf t) J q.state)
      match hst : q.state with
      | .reversing ok (x :: f) f' (y :: r) r' =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (revD x y) by rw [hst]; rfl,
            show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (revD x y) ?_
          intro ro; cases ro <;> simp [revD, dApply, sRoleList, hst, RTQueue.exec]
      | .reversing ok [] f' [y] r' =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (appStartD y) by rw [hst]; rfl,
            show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (appStartD y) ?_
          intro ro; cases ro <;> simp [appStartD, dApply, sRoleList, hst, RTQueue.exec]
      | .reversing ok [] f' [] r' =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl, show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.exec]
      | .reversing ok [] f' (y :: z :: r) r' =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl, show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.exec]
      | .reversing ok (x :: f) f' [] r' =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl, show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.exec]
      | .appending 0 f' r' =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl,
            show execJunk (roleOf t) J q.state
              = ovrL (roleOf t .fwd') (f' ++ J (roleOf t .fwd')) J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;>
            simp [dApply, sRoleList, hst, RTQueue.exec, ovrL, sinj_iff hinj]
      | .appending (n + 1) (x :: f') r' =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (appD x) by rw [hst]; rfl,
            show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (appD x) ?_
          intro ro; cases ro <;> simp [appD, dApply, sRoleList, hst, RTQueue.exec]
      | .appending (n + 1) [] r' =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl, show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.exec]
      | .idle =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl, show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.exec]
      | .done f0 =>
          rw [show execDelta (roleOf t) q.state = toAddr (roleOf t) (fun _ => .keep) by
              rw [hst]; rfl, show execJunk (roleOf t) J q.state = J by rw [hst]; rfl]
          refine laysS_delta hinj h (fun _ => .keep) ?_
          intro ro; cases ro <;> simp [dApply, sRoleList, hst, RTQueue.exec]
  | install =>
      show LaysS (finish q) (roleOf (if isDone q.state then doneTag t else t))
        (fun i => dApply (toAddr (roleOf t) (fun _ => Delta.keep) i) (L i))
        (if isDone q.state then ovrL (roleOf t .front) (q.front ++ J (roleOf t .front)) J else J)
      rw [dApply_keep_fam]
      by_cases hd : isDone q.state = true
      · obtain ⟨f0, hst⟩ := isDone_eq hd
        rw [if_pos hd, if_pos hd, roleOf_doneTag]
        intro ro
        show L (doneRolesS (roleOf t) ro) = _
        cases ro <;>
          simp [doneRolesS, donePerm, hL, sRoleList, finish, hst, ovrL, sinj_iff hinj]
      · rw [if_neg hd, if_neg hd]
        have hst : finish q = q := by
          unfold finish
          cases hq : q.state with
          | done f0 => exact absurd (by simp [isDone, hq]) hd
          | idle => simp [hq]
          | reversing ok f f' r r' => simp [hq]
          | appending ok f' r' => simp [hq]
        rw [hst]; exact h


end PalPeg.CloseoutCoreEnc25
