import PalPeg.ScaFlagsLink

/-!
# The reader liveness of the flag table, by certificate

`ScaFlagsLink.ReaderFacts` states four facts about the reader liveness `liveReaders` of the flag
table (`GsHeadLiveness.analyzeReaders`) and the reader colouring. The kernel cannot run
`liveReaders` itself (a Gauss–Seidel iteration over strings). As for the distance liveness in
`ScaWorkerRegs`, a certificate stands in for it:

* `readerCertN`: the live readers of every row, as indices into `names` (generated by `#eval`
  of `liveReaders`, pasted as a literal); `readerCert` decodes it to head names.
* `rowOk` checks, row by row, that the certificate is a post-fixpoint of `readerTransfer`, that
  the reader colouring is proper on its after-sets, and that its live heads are coloured;
  `rows_ok` evaluates it by `decide +kernel` over all 492 rows, in five pieces.
* `readerTransfer` is monotone and keeps lists duplicate-free (`transfer_mono`,
  `transfer_nodup`), and the certificate is small (`weight_lt`), so
  `ScaWorkerRegs.fixpoint_spec` puts `liveReaders` below the certificate row by row and shows it
  is itself a post-fixpoint (`liveReaders_spec`).
* `readerFacts : ScaFlagsLink.ReaderFacts` follows, for every row (not only the certified ones).
-/

set_option autoImplicit false

namespace PalPeg.ScaFlagsReaders

open PalPeg.ScaGsProgram PalPeg.ScaWindowWorker PalPeg.ScaHeadVM PalPeg.ScaFlagsLink

/-! ## The certificate -/

/-- The live readers before every row of the flag table, as indices into `fspec.names`. -/
def readerCertN : List (List Nat) := [
  /- 0 -/ [], [0, 1, 14], [0, 1, 14], [0, 1, 14], [0, 1, 14], [0, 1, 14], [0, 4, 1], [],
  /- 8 -/ [0, 4, 1], [], [0, 4, 1], [], [], [0, 4, 1, 3], [], [0, 4, 1, 3, 5],
  /- 16 -/ [0, 4, 1, 3, 5, 7], [0, 4, 1, 3, 5, 7], [0, 4, 1, 3, 5, 7, 6], [0, 4, 1, 3, 5, 7, 6], [0, 4, 1, 3, 5, 7, 6], [0, 4, 1, 3], [0, 3, 4, 5, 7, 1, 6], [7, 0, 4, 1, 3],
  /- 24 -/ [0, 3, 4, 5, 7, 1, 6], [0, 3, 4, 5, 7, 1, 6], [7, 0, 4, 1, 3], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5, 6], [0, 3, 4, 5, 7, 1, 6], [7, 0, 4, 1, 3], [0, 3, 4, 5, 7, 1],
  /- 32 -/ [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5, 6], [0, 3, 4, 5, 7, 1, 6], [7, 0, 5, 4, 1], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3, 5, 7], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3, 5, 7],
  /- 40 -/ [0, 1, 4, 3, 5, 6], [7, 0, 5, 6, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3], [0, 1, 4, 3, 5, 6], [7, 0, 5, 6, 4, 1], [0, 3, 4, 5, 7, 1],
  /- 48 -/ [0, 3, 4, 5, 7, 1], [0, 1, 4, 3], [0, 1, 4, 3, 5, 6], [7, 0, 5, 6, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5], [7, 0, 5, 6, 4, 1],
  /- 56 -/ [7, 0, 5, 6, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5, 7], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1],
  /- 64 -/ [0, 1, 4, 3, 5, 7], [7, 0, 5, 6, 4, 1], [0, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5, 6, 7], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1],
  /- 72 -/ [0, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5, 6, 7], [7, 0, 5, 6, 4, 1], [7, 0, 5, 4, 1], [7, 0, 5, 6, 4, 1], [0, 4, 1],
  /- 80 -/ [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5, 6, 7], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 4, 1, 10], [0, 4, 1], [0, 4, 1],
  /- 88 -/ [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3], [0, 1, 4, 3, 5, 6, 7], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 4, 1, 10, 6],
  /- 96 -/ [0, 4, 1], [0, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [7, 0, 1, 4, 3], [0, 1, 4, 3, 5, 6, 7], [0, 3, 4, 5, 6, 7, 1], [7, 0, 5, 6, 4, 1],
  /- 104 -/ [7, 0, 5, 6, 4, 1], [7, 0, 5, 4, 1], [7, 0, 5, 4, 1, 10, 6], [0, 4, 1], [0, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [7, 0, 1, 4, 3],
  /- 112 -/ [0, 1, 4, 3, 5, 6, 7], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 6, 7, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 4, 1], [7, 0, 5, 1, 4], [7, 0, 5, 4, 1, 10, 6],
  /- 120 -/ [0, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [7, 0, 1, 4, 3], [0, 1, 4, 3, 5, 6, 7], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 6, 7, 1],
  /- 128 -/ [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 1, 4], [0, 4, 1], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [7, 0, 5, 1, 4], [0, 1, 4, 3, 5, 6, 7],
  /- 136 -/ [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5, 7], [0, 3, 4, 5, 7, 1], [0, 1, 4, 3, 5, 7], [0, 4, 1, 3, 5, 6, 7], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 4, 1],
  /- 144 -/ [7, 0, 5, 4, 1], [0, 4, 1, 3], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [7, 0, 5, 6, 1, 4], [0, 1, 4, 3, 5, 6, 7], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1],
  /- 152 -/ [0, 4, 1, 3], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 4, 1], [7, 0, 5, 4, 1], [0, 4, 1, 3, 5], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1],
  /- 160 -/ [7, 0, 5, 6, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [7, 0, 5, 4, 1], [7, 0, 5, 4, 1],
  /- 168 -/ [0, 4, 1, 3, 5, 7], [7, 0, 5, 6, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3, 5], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [0, 4, 1, 3, 5, 7],
  /- 176 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3, 5, 7], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [0, 4, 1, 3, 5, 7, 6],
  /- 184 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3, 5, 7], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [0, 4, 1, 3, 5, 7, 6],
  /- 192 -/ [7, 0, 5, 6, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3, 5, 7, 6], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [0, 4, 1, 3, 5, 7, 6], [7, 0, 5, 6, 1, 4],
  /- 200 -/ [7, 0, 5, 6, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3, 5, 7, 6], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [0, 4, 1, 3], [3, 5, 7, 0, 4, 1, 6],
  /- 208 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4], [7, 0, 5, 6, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [0, 4, 1, 3, 5, 7, 6], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1],
  /- 216 -/ [7, 0, 4, 1, 3], [3, 5, 7, 0, 4, 1, 6], [3, 5, 7, 0, 4, 1, 6], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4, 10], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1],
  /- 224 -/ [0, 4, 1, 3, 5, 7, 6], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 6], [3, 5, 7, 0, 4, 1, 6], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4],
  /- 232 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4, 10, 6], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [5, 7, 0, 3, 4, 1, 6], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [3, 5, 7, 0, 4, 1],
  /- 240 -/ [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 6], [3, 5, 7, 0, 4, 1, 6], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4],
  /- 248 -/ [7, 0, 5, 1, 4, 10, 6], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1, 6], [7, 0, 5, 6, 4, 1], [7, 0, 5, 6, 4, 1], [3, 5, 7, 0, 4, 1],
  /- 256 -/ [0, 4, 1, 3, 5, 7], [3, 5, 7, 0, 4, 1], [0, 4, 1, 3, 5, 7], [0, 1, 4, 3, 5, 6], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4],
  /- 264 -/ [7, 0, 5, 1, 4], [7, 0, 5, 1, 4, 10, 6], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [5, 7, 0, 3, 4, 1], [0, 4, 1, 3], [5, 7, 0, 3, 4, 1, 6], [3, 5, 7, 0, 4, 1],
  /- 272 -/ [3, 5, 7, 0, 4, 1], [0, 1, 4, 3], [0, 1, 4, 3, 5, 6], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1],
  /- 280 -/ [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [0, 4, 1, 3], [5, 7, 0, 3, 4, 1, 6], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3], [0, 1, 4, 3, 5, 6],
  /- 288 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4], [7, 0, 5, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [5, 7, 0, 3, 4, 1], [0, 4, 1, 3, 5, 7],
  /- 296 -/ [5, 7, 0, 3, 4, 1], [0, 4, 1, 3, 5, 7], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4],
  /- 304 -/ [7, 0, 5, 1, 4], [0, 3, 4, 5, 7, 1], [0, 3, 4, 5, 7, 1], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 7],
  /- 312 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [7, 0, 5, 1, 4], [7, 0, 5, 1, 4], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1],
  /- 320 -/ [0, 1, 4, 3, 5, 7], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 6, 7],
  /- 328 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 6, 7], [7, 0, 5, 6, 1, 4],
  /- 336 -/ [7, 0, 5, 6, 1, 4], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 6, 7], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4],
  /- 344 -/ [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3], [0, 1, 4, 3, 5, 6, 7], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4],
  /- 352 -/ [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [7, 0, 1, 4, 3], [0, 1, 4, 3, 5, 6, 7], [0, 3, 4, 5, 6, 7, 1], [7, 0, 5, 6, 1, 4],
  /- 360 -/ [7, 0, 5, 6, 1, 4], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 6, 7], [3, 5, 7, 0, 4, 1], [0, 3, 4, 5, 6, 7, 1],
  /- 368 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 6, 7], [3, 5, 7, 0, 4, 1],
  /- 376 -/ [3, 5, 7, 0, 4, 1], [0, 3, 4, 5, 6, 7, 1], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1],
  /- 384 -/ [0, 1, 4, 3, 5, 6, 7], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 7], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 7], [0, 4, 1, 3, 5, 6, 7], [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4],
  /- 392 -/ [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 1, 4, 3, 5, 6, 7], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 4, 1, 3],
  /- 400 -/ [7, 0, 5, 6, 1, 4], [7, 0, 5, 6, 1, 4], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1],
  /- 408 -/ [0, 4, 1, 3], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 4, 1, 3, 5], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1],
  /- 416 -/ [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 4, 1, 3, 5, 7], [5, 7, 0, 3, 4, 1], [5, 7, 0, 3, 4, 1], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 4, 1, 3, 5, 7],
  /- 424 -/ [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 4, 1, 3, 5, 7, 6], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 4, 1, 3, 5, 7, 6], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1],
  /- 432 -/ [0, 4, 1, 3, 5, 7, 6], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [0, 4, 1, 3, 5, 7, 6], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [5, 7, 3, 0, 4, 1, 6], [3, 5, 7, 0, 4, 1],
  /- 440 -/ [3, 5, 7, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1, 6], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [5, 7, 3, 0, 4, 1], [0, 4, 1, 3], [5, 7, 3, 0, 4, 1, 6],
  /- 448 -/ [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [0, 4, 1, 3], [5, 7, 3, 0, 4, 1, 6], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1],
  /- 456 -/ [5, 7, 3, 0, 4, 1], [0, 4, 1, 3, 5, 7], [5, 7, 3, 0, 4, 1], [0, 4, 1, 3, 5, 7], [3, 5, 7, 0, 4, 1], [3, 5, 7, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1],
  /- 464 -/ [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1],
  /- 472 -/ [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1],
  /- 480 -/ [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1],
  /- 488 -/ [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1], [5, 7, 3, 0, 4, 1]
]

/-- The certificate, decoded to head names. -/
def readerCert : Array (List String) :=
  (readerCertN.map fun l => l.map fun i => fspec.names.getD i "").toArray

/-! ## The checks -/

/-- Row `r`: the certificate is a post-fixpoint of `readerTransfer`, the colouring is proper on
the after-set, the live heads are coloured. -/
def rowOk (r : Nat) (row : Row) : Bool :=
  let before := readerCert.getD r []
  let after := successorsUnion readerCert row.targets
  let cs := after.map fun h => (h, color fspec h)
  (readerTransfer row after).all (fun x => decide (x ∈ before)) &&
  cs.all (fun c => cs.all fun c' => decide (c.1 = c'.1) || c.2.isNone || decide (c.2 ≠ c'.2)) &&
  before.all (fun h => (color fspec h).isSome)

/-- `rowOk` on the rows `lo, …, lo + n - 1`. -/
def rowsOk (lo n : Nat) : Bool :=
  (List.range' lo n).all fun r =>
    match fspec.program.code[r]? with
    | some row => rowOk r row
    | none => true

theorem rowsOk_append (lo a b : Nat) :
    rowsOk lo (a + b) = (rowsOk lo a && rowsOk (lo + a) b) := by
  unfold rowsOk
  rw [← List.all_append]
  congr 1
  simp

theorem rowsOk_split (lo a b : Nat) (hfirst : rowsOk lo a = true)
    (hrest : rowsOk (lo + a) b = true) : rowsOk lo (a + b) = true := by
  rw [rowsOk_append, hfirst, hrest]
  rfl

set_option maxRecDepth 100000

theorem rows_0 : rowsOk 0 100 = true := by decide +kernel

theorem rows_100 : rowsOk 100 100 = true := by decide +kernel

theorem rows_200 : rowsOk 200 100 = true := by decide +kernel

theorem rows_300 : rowsOk 300 100 = true := by decide +kernel

theorem rows_400 : rowsOk 400 92 = true := by decide +kernel

theorem rows_ok : rowsOk 0 fspec.program.code.length = true := by
  rw [ScaWorkerRegs.flags_code_length]
  exact rowsOk_split 0 100 392 rows_0
    (rowsOk_split 100 100 292 rows_100
    (rowsOk_split 200 100 192 rows_200
    (rowsOk_split 300 100 92 rows_300 rows_400)))

/-- Every certificate entry has at most `7` heads. -/
theorem lengths_ok : readerCertN.all (fun l => decide (l.length ≤ 7)) = true := by decide +kernel

/-- At the start row only `Origin`, `TextOrigin`, `OriginalEnd` are in the certificate. -/
theorem start_ok :
    (readerCert.getD fspec.program.start []).all
      (fun h => decide (h = "Origin" ∨ h = "TextOrigin" ∨ h = "OriginalEnd")) = true := by
  decide +kernel

/-! ## `readerTransfer` is monotone and duplicate-free -/

theorem transfer_mono (row : Row) (xs ys : List String) (hsub : xs ⊆ ys) :
    readerTransfer row xs ⊆ readerTransfer row ys := by
  obtain ⟨ev, targets⟩ := row
  intro x hx
  cases ev with
  | copy t src =>
    change x ∈ (if t ∈ xs then union (xs.filter fun y => decide (y ≠ t)) [src] else xs) at hx
    change x ∈ (if t ∈ ys then union (ys.filter fun y => decide (y ≠ t)) [src] else ys)
    by_cases htx : t ∈ xs
    · have hty : t ∈ ys := hsub htx
      rw [if_pos htx, ScaWorkerRegs.mem_union] at hx
      rw [if_pos hty, ScaWorkerRegs.mem_union]
      rcases hx with hx | hx
      · rw [List.mem_filter] at hx
        exact Or.inl (List.mem_filter.mpr ⟨hsub hx.1, hx.2⟩)
      · exact Or.inr hx
    · rw [if_neg htx] at hx
      by_cases hty : t ∈ ys
      · rw [if_pos hty, ScaWorkerRegs.mem_union]
        refine Or.inl (List.mem_filter.mpr ⟨hsub hx, ?_⟩)
        simp only [ne_eq, decide_eq_true_eq]
        rintro rfl
        exact htx hx
      · rw [if_neg hty]
        exact hsub hx
  | symbols l r =>
    change x ∈ union xs [l, r] at hx
    change x ∈ union ys [l, r]
    rw [ScaWorkerRegs.mem_union] at hx ⊢
    rcases hx with hx | hx
    · exact Or.inl (hsub hx)
    · exact Or.inr hx
  | available h =>
    change x ∈ union xs [h] at hx
    change x ∈ union ys [h]
    rw [ScaWorkerRegs.mem_union] at hx ⊢
    rcases hx with hx | hx
    · exact Or.inl (hsub hx)
    · exact Or.inr hx
  | move ms => exact hsub hx
  | equal a b => exact hsub hx
  | less a b => exact hsub hx
  | border h => exact hsub hx
  | flag b => exact hsub hx
  | assertEqual a b => exact hsub hx
  | «match» h => exact hsub hx
  | halt => exact hsub hx

theorem transfer_nodup (row : Row) (xs : List String) (hxs : xs.Nodup) :
    (readerTransfer row xs).Nodup := by
  obtain ⟨ev, targets⟩ := row
  cases ev with
  | copy t src =>
    change (if t ∈ xs then union (xs.filter fun y => decide (y ≠ t)) [src] else xs).Nodup
    split
    · exact ScaWorkerRegs.union_nodup _ _ (hxs.filter _)
    · exact hxs
  | symbols l r => exact ScaWorkerRegs.union_nodup xs [l, r] hxs
  | available h => exact ScaWorkerRegs.union_nodup xs [h] hxs
  | move ms => exact hxs
  | equal a b => exact hxs
  | less a b => exact hxs
  | border h => exact hxs
  | flag b => exact hxs
  | assertEqual a b => exact hxs
  | «match» h => exact hxs
  | halt => exact hxs

/-! ## The certificate is a small post-fixpoint -/

theorem rowOk_of_code {r : Nat} {row : Row} (hrow : fspec.program.code[r]? = some row) :
    rowOk r row = true := by
  have hlt : r < fspec.program.code.length := (List.getElem?_eq_some_iff.mp hrow).1
  have hall := List.all_eq_true.mp rows_ok r (List.mem_range'_1.mpr ⟨Nat.zero_le _, by omega⟩)
  rw [hrow] at hall
  exact hall

/-- `rowOk`, unpacked. -/
theorem rowOk_spec {r : Nat} {row : Row} (hok : rowOk r row = true) :
    (∀ x ∈ readerTransfer row (successorsUnion readerCert row.targets),
      x ∈ readerCert.getD r []) ∧
    Proper fspec (successorsUnion readerCert row.targets) ∧
    Colored fspec (readerCert.getD r []) := by
  simp only [rowOk, Bool.and_eq_true, List.all_eq_true, decide_eq_true_eq] at hok
  obtain ⟨⟨hfix, hproper⟩, hcolored⟩ := hok
  refine ⟨hfix, ?_, ?_⟩
  · intro h hA h' hA' i hc hc'
    have hpair := hproper (h, color fspec h) (List.mem_map.mpr ⟨h, hA, rfl⟩)
      (h', color fspec h') (List.mem_map.mpr ⟨h', hA', rfl⟩)
    rw [hc, hc'] at hpair
    simpa using hpair
  · intro h hh
    have hsome := hcolored h hh
    obtain ⟨i, hi⟩ := Option.isSome_iff_exists.mp hsome
    exact ⟨i, hi⟩

theorem postFix : ScaWorkerRegs.PostFix fspec.program.code readerTransfer readerCert :=
  fun _ _ hrow => (rowOk_spec (rowOk_of_code hrow)).1

theorem getD_length_le (r : Nat) : (readerCert.getD r []).length ≤ 7 := by
  have hall := List.all_eq_true.mp lengths_ok
  unfold readerCert
  rw [Array.getD_eq_getD_getElem?, List.getElem?_toArray]
  cases hget : (readerCertN.map fun l => l.map fun i => fspec.names.getD i "")[r]? with
  | none => simp
  | some l =>
    rw [List.getElem?_map] at hget
    cases hl : readerCertN[r]? with
    | none => rw [hl] at hget; cases hget
    | some l0 =>
      rw [hl] at hget
      cases hget
      have h7 := hall l0 (List.mem_of_getElem? hl)
      simp only [decide_eq_true_eq] at h7
      simpa using h7

theorem weight_lt :
    ScaWorkerRegs.weight fspec.program.code readerCert <
      fspec.program.code.length * fspec.names.length + 1 := by
  have hle : ScaWorkerRegs.weight fspec.program.code readerCert ≤
      ∑ _r ∈ Finset.range fspec.program.code.length, 7 :=
    Finset.sum_le_sum fun r _ => getD_length_le r
  rw [Finset.sum_const, Finset.card_range, smul_eq_mul] at hle
  have hnames : fspec.names.length = 18 := rfl
  rw [hnames]
  omega

/-- **`liveReaders` against the certificate**: below it row by row, and a post-fixpoint. -/
theorem liveReaders_spec :
    ScaWorkerRegs.Approx fspec.program.code readerTransfer readerCert (liveReaders fspec) ∧
      ScaWorkerRegs.PostFix fspec.program.code readerTransfer (liveReaders fspec) :=
  ScaWorkerRegs.fixpoint_spec transfer_mono transfer_nodup postFix weight_lt

/-! ## The reader facts -/

theorem live_sub_cert (r : Nat) : ∀ h ∈ live r, h ∈ readerCert.getD r [] :=
  fun _ hh => liveReaders_spec.1.below r hh

/-- **The reader facts of the flag table**, for every row. -/
theorem readerFacts : ReaderFacts where
  fix := fun _ _ r row _ hrow _ hx => liveReaders_spec.2 r row hrow hx
  proper := fun _ _ _ row _ hrow h hA h' hA' i hc hc' =>
    (rowOk_spec (rowOk_of_code hrow)).2.1 h
      (ScaWorkerRegs.successorsUnion_mono liveReaders_spec.1.below row.targets hA) h'
      (ScaWorkerRegs.successorsUnion_mono liveReaders_spec.1.below row.targets hA') i hc hc'
  colored := fun _ _ r hsim h hh => by
    obtain ⟨row, hrow, -⟩ := ScaGsCert.sim_step ScaGsCertData.flags_certOk hsim
    exact (rowOk_spec (rowOk_of_code hrow)).2.2 h (live_sub_cert r h hh)
  startLive := fun h hh => by
    have hmem := live_sub_cert fspec.program.start h hh
    have hall := List.all_eq_true.mp start_ok h hmem
    simpa using hall

end PalPeg.ScaFlagsReaders
