import PalPeg.ScaFlagsReaders

/-!
# The reader liveness of the matcher table, by certificate

The matcher counterpart of `ScaFlagsReaders`: five facts about the reader liveness
`liveReaders` of `ScaGsTables.matcherWorker` (294 rows) and its reader colouring, proved
without running `liveReaders` in the kernel.

* **Upper bounds** (`fix`, `proper`, `colored`, `startLive`). A certificate
  `matcherReadersN` (the live readers of every row as indices into `names`, generated by
  `#eval` of `liveReaders`, pasted as a literal) is checked by `decide +kernel` to be a
  post-fixpoint of `readerTransfer` with a proper colouring on its after-sets (`rowsOk`), with
  coloured entries of at most `6` heads (`entriesOk`) and only `Origin`/`Tail` at the start row.
  `ScaWorkerRegs.fixpoint_spec` then puts the real `liveReaders` below the certificate and
  shows it is itself a post-fixpoint (`liveReaders_spec_of_cert`).
* **A lower bound** (`matchB`). `readerTransfer` adds nothing at a `match` row, so `B` is live
  there only through a successor. A post-fixpoint contains `h` at every row from which a path
  reaches a row reading `h` (`symbols`/`available`) without passing a copy into `h`
  (`live_of_pathOk`). The two match rows get explicit paths: row 84 via 54, 59, 35, 41 to the
  `available "B"` row 46, and row 203 via 163, 171, 179, 137, 144 to the `available "B"` row 151
  (`matchPaths`, checked by `matchOk`).

The generic part (`decode`, `rowOk`, `entriesOk`, `pathOk` and their soundness) takes the
worker spec as a parameter; `transfer_mono` / `transfer_nodup` are reused from
`ScaFlagsReaders`.
-/

set_option autoImplicit false

namespace PalPeg.ScaMatcherReaders

open PalPeg.ScaGsProgram PalPeg.ScaWindowWorker PalPeg.ScaHeadVM

/-! ## A reader certificate for a worker table -/

section Generic

variable (spec : WorkerSpec)

/-- A certificate of head indices, decoded to head names. -/
def decode (CN : List (List Nat)) : Array (List String) :=
  (CN.map fun l => l.map fun i => spec.names.getD i "").toArray

/-- Row `r`: `cert` is a post-fixpoint of `readerTransfer` there, and the reader colouring is
proper on the row's after-set. -/
def rowOk (cert : Array (List String)) (r : Nat) (row : Row) : Bool :=
  let after := successorsUnion cert row.targets
  let cs := after.map fun h => (h, color spec h)
  (readerTransfer row after).all (fun x => decide (x ∈ cert.getD r [])) &&
  cs.all (fun c => cs.all fun c' => decide (c.1 = c'.1) || c.2.isNone || decide (c.2 ≠ c'.2))

/-- `rowOk` on the rows `lo, …, lo + n - 1`. -/
def rowsOk (cert : Array (List String)) (lo n : Nat) : Bool :=
  (List.range' lo n).all fun r =>
    match spec.program.code[r]? with
    | some row => rowOk spec cert r row
    | none => true

/-- Every entry has at most `m` heads, all of them coloured. -/
def entriesOk (CN : List (List Nat)) (m : Nat) : Bool :=
  CN.all fun l => decide (l.length ≤ m) && l.all fun i => (color spec (spec.names.getD i "")).isSome

/-- Row `row` reads head `h`. -/
def reads (h : String) (row : Row) : Bool :=
  match row.event with
  | .symbols l r => decide (l = h) || decide (r = h)
  | .available g => decide (g = h)
  | _ => false

/-- Row `row` copies into head `h`. -/
def copiesTo (h : String) (row : Row) : Bool :=
  match row.event with
  | .copy t _ => decide (t = h)
  | _ => false

/-- A path of rows, each a successor of the previous, none copying into `h`, ending at a row
that reads `h`. -/
def pathOk (h : String) : List Nat → Bool
  | [] => false
  | [r] =>
    match spec.program.code[r]? with
    | some row => reads h row
    | none => false
  | r :: t :: rest =>
    match spec.program.code[r]? with
    | some row => !copiesTo h row && decide (t ∈ row.targets) && pathOk h (t :: rest)
    | none => false

/-- Every `match` row has a checked path to a row reading `B`. -/
def matchOk (paths : List (Nat × List Nat)) : Bool :=
  (List.range spec.program.code.length).all fun r =>
    match spec.program.code[r]? with
    | some row =>
      match row.event with
      | .«match» _ =>
        match paths.lookup r with
        | some p => pathOk spec "B" (r :: p)
        | none => false
      | _ => true
    | none => true

variable {spec}

theorem rowsOk_append (cert : Array (List String)) (lo a b : Nat) :
    rowsOk spec cert lo (a + b) = (rowsOk spec cert lo a && rowsOk spec cert (lo + a) b) := by
  unfold rowsOk
  rw [← List.all_append]
  congr 1
  simp

theorem rowsOk_split {cert : Array (List String)} (lo a b : Nat)
    (hfirst : rowsOk spec cert lo a = true) (hrest : rowsOk spec cert (lo + a) b = true) :
    rowsOk spec cert lo (a + b) = true := by
  rw [rowsOk_append, hfirst, hrest]
  rfl

theorem decode_getD (CN : List (List Nat)) (r : Nat) :
    (decode spec CN).getD r [] =
      ((CN[r]?).map fun l => l.map fun i => spec.names.getD i "").getD [] := by
  unfold decode
  rw [Array.getD_eq_getD_getElem?, List.getElem?_toArray, List.getElem?_map]

theorem rowOk_of_rows {cert : Array (List String)}
    (hrows : rowsOk spec cert 0 spec.program.code.length = true) {r : Nat} {row : Row}
    (hrow : spec.program.code[r]? = some row) : rowOk spec cert r row = true := by
  have hlt : r < spec.program.code.length := (List.getElem?_eq_some_iff.mp hrow).1
  have hall := List.all_eq_true.mp hrows r (List.mem_range'_1.mpr ⟨Nat.zero_le _, by omega⟩)
  rw [hrow] at hall
  exact hall

theorem rowOk_spec {cert : Array (List String)} {r : Nat} {row : Row}
    (hok : rowOk spec cert r row = true) :
    (∀ x ∈ readerTransfer row (successorsUnion cert row.targets), x ∈ cert.getD r []) ∧
      Proper spec (successorsUnion cert row.targets) := by
  simp only [rowOk, Bool.and_eq_true, List.all_eq_true, decide_eq_true_eq] at hok
  obtain ⟨hfix, hproper⟩ := hok
  refine ⟨hfix, ?_⟩
  intro h hA h' hA' i hc hc'
  have hpair := hproper (h, color spec h) (List.mem_map.mpr ⟨h, hA, rfl⟩)
    (h', color spec h') (List.mem_map.mpr ⟨h', hA', rfl⟩)
  rw [hc, hc'] at hpair
  simpa using hpair

/-- `entriesOk`, for every row index (out of range the certificate is empty). -/
theorem entries_spec {CN : List (List Nat)} {m : Nat} (hentries : entriesOk spec CN m = true)
    (r : Nat) :
    ((decode spec CN).getD r []).length ≤ m ∧ Colored spec ((decode spec CN).getD r []) := by
  rw [decode_getD]
  cases hl : CN[r]? with
  | none => exact ⟨by simp, fun _ hh => by simp at hh⟩
  | some l =>
    have hent := List.all_eq_true.mp hentries l (List.mem_of_getElem? hl)
    simp only [Bool.and_eq_true, decide_eq_true_eq, List.all_eq_true] at hent
    obtain ⟨hlen, hcol⟩ := hent
    refine ⟨by simpa using hlen, ?_⟩
    intro h hh
    simp only [Option.map_some, Option.getD_some, List.mem_map] at hh
    obtain ⟨i, hi, rfl⟩ := hh
    exact Option.isSome_iff_exists.mp (hcol i hi)

/-- **`liveReaders` against a certificate**: below it row by row, and a post-fixpoint. -/
theorem liveReaders_spec_of_cert {CN : List (List Nat)} {m : Nat}
    (hrows : rowsOk spec (decode spec CN) 0 spec.program.code.length = true)
    (hentries : entriesOk spec CN m = true) (hm : m ≤ spec.names.length) :
    ScaWorkerRegs.Approx spec.program.code readerTransfer (decode spec CN) (liveReaders spec) ∧
      ScaWorkerRegs.PostFix spec.program.code readerTransfer (liveReaders spec) := by
  have hpost : ScaWorkerRegs.PostFix spec.program.code readerTransfer (decode spec CN) :=
    fun _ _ hrow => (rowOk_spec (rowOk_of_rows hrows hrow)).1
  have hle : ScaWorkerRegs.weight spec.program.code (decode spec CN) ≤
      ∑ _r ∈ Finset.range spec.program.code.length, m :=
    Finset.sum_le_sum fun r _ => (entries_spec hentries r).1
  rw [Finset.sum_const, Finset.card_range, smul_eq_mul] at hle
  have hweight : ScaWorkerRegs.weight spec.program.code (decode spec CN) <
      spec.program.code.length * spec.names.length + 1 := by
    have := Nat.mul_le_mul_left spec.program.code.length hm
    omega
  exact ScaWorkerRegs.fixpoint_spec ScaFlagsReaders.transfer_mono ScaFlagsReaders.transfer_nodup
    hpost hweight

/-! ### Lower bounds along paths -/

theorem mem_transfer_of_reads {h : String} {row : Row} (hreads : reads h row = true)
    (succ : List String) : h ∈ readerTransfer row succ := by
  obtain ⟨ev, targets⟩ := row
  cases ev with
  | symbols l r =>
    change h ∈ union succ [l, r]
    rw [ScaWorkerRegs.mem_union]
    simp only [reads, Bool.or_eq_true, decide_eq_true_eq] at hreads
    rcases hreads with rfl | rfl <;> simp
  | available g =>
    change h ∈ union succ [g]
    rw [ScaWorkerRegs.mem_union]
    simp only [reads, decide_eq_true_eq] at hreads
    subst hreads
    simp
  | _ => simp [reads] at hreads

theorem mem_transfer_of_mem {h : String} {row : Row} (hcopy : copiesTo h row = false)
    {succ : List String} (hh : h ∈ succ) : h ∈ readerTransfer row succ := by
  obtain ⟨ev, targets⟩ := row
  cases ev with
  | copy t src =>
    change h ∈ (if t ∈ succ then union (succ.filter fun y => decide (y ≠ t)) [src] else succ)
    simp only [copiesTo, decide_eq_false_iff_not] at hcopy
    split
    · rw [ScaWorkerRegs.mem_union]
      refine Or.inl (List.mem_filter.mpr ⟨hh, ?_⟩)
      simp only [ne_eq, decide_eq_true_eq]
      exact fun heq => hcopy heq.symm
    · exact hh
  | symbols l r =>
    change h ∈ union succ [l, r]
    exact (ScaWorkerRegs.mem_union _ _ _).mpr (Or.inl hh)
  | available g =>
    change h ∈ union succ [g]
    exact (ScaWorkerRegs.mem_union _ _ _).mpr (Or.inl hh)
  | move ms => exact hh
  | equal a b => exact hh
  | less a b => exact hh
  | border g => exact hh
  | flag b => exact hh
  | assertEqual a b => exact hh
  | «match» g => exact hh
  | halt => exact hh

/-- **A post-fixpoint holds `h` along a path** that reaches a row reading `h` without a copy
into `h`. -/
theorem live_of_pathOk {bs : Array (List String)}
    (hpost : ScaWorkerRegs.PostFix spec.program.code readerTransfer bs) {h : String} :
    ∀ (rest : List Nat) (r : Nat), pathOk spec h (r :: rest) = true → h ∈ bs.getD r []
  | [], r, hpath => by
    unfold pathOk at hpath
    cases hrow : spec.program.code[r]? with
    | none => rw [hrow] at hpath; cases hpath
    | some row =>
      rw [hrow] at hpath
      exact hpost r row hrow (mem_transfer_of_reads hpath _)
  | t :: rest, r, hpath => by
    unfold pathOk at hpath
    cases hrow : spec.program.code[r]? with
    | none => rw [hrow] at hpath; cases hpath
    | some row =>
      rw [hrow] at hpath
      simp only [Bool.and_eq_true, Bool.not_eq_true', decide_eq_true_eq] at hpath
      obtain ⟨⟨hcopy, ht⟩, hnext⟩ := hpath
      have hlive := live_of_pathOk hpost rest t hnext
      exact hpost r row hrow (mem_transfer_of_mem hcopy
        ((ScaWorkerRegs.mem_successorsUnion _ _ _).mpr ⟨t, ht, hlive⟩))

theorem matchB_of_check {bs : Array (List String)}
    (hpost : ScaWorkerRegs.PostFix spec.program.code readerTransfer bs)
    {paths : List (Nat × List Nat)} (hcheck : matchOk spec paths = true) :
    ∀ r row, spec.program.code[r]? = some row → ∀ h, row.event = .«match» h →
      "B" ∈ bs.getD r [] := by
  intro r row hrow h hev
  have hlt : r < spec.program.code.length := (List.getElem?_eq_some_iff.mp hrow).1
  have hall := List.all_eq_true.mp hcheck r (List.mem_range.mpr hlt)
  rw [hrow] at hall
  simp only [hev] at hall
  cases hp : paths.lookup r with
  | none => rw [hp] at hall; cases hall
  | some p =>
    rw [hp] at hall
    exact live_of_pathOk hpost p r hall

end Generic

/-! ## The matcher table -/

/-- The live readers before every row of the matcher table, as indices into its `names`. -/
def matcherReadersN : List (List Nat) := [
  /- 0 -/ [], [0, 4], [0, 4], [0, 3, 4], [0, 3, 4, 5], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7, 6],
  /- 8 -/ [0, 3, 4, 5, 7, 6], [0, 3, 4, 5, 7, 6], [0, 3, 4], [0, 3, 4, 5, 7, 6], [7, 0, 3], [0, 3, 4, 5, 7, 6], [0, 3, 4, 5, 7, 6], [7, 0, 3],
  /- 16 -/ [0, 3, 4, 5, 7], [0, 3, 4, 5, 6], [0, 3, 4, 5, 7, 6], [5, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 6], [0, 3, 4, 5, 7, 6],
  /- 24 -/ [5, 6, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 6], [5, 6, 7, 0], [0, 3, 4, 5, 7],
  /- 32 -/ [0, 3, 4, 5, 7], [0, 3, 4], [0, 3, 4, 5, 6], [5, 6, 7, 0], [6, 5, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4],
  /- 40 -/ [0, 3, 4, 5, 6], [5, 6, 10, 7, 0], [5, 6, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7],
  /- 48 -/ [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 6, 7, 0, 10, 14], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0],
  /- 56 -/ [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 6, 7], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7],
  /- 64 -/ [0, 3, 4, 5, 6, 7], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [5, 6, 7, 0, 10, 14], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7],
  /- 72 -/ [0, 3, 4, 5, 6, 7], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7],
  /- 80 -/ [0, 3, 4], [0, 3, 4, 5, 6, 7], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7],
  /- 88 -/ [0, 3, 4, 5, 7], [7, 0, 3], [0, 3, 4, 5, 6, 7], [0, 3, 4, 5, 6, 7], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0, 10, 14],
  /- 96 -/ [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [7, 0, 3], [0, 3, 4, 5, 6, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 6, 7], [5, 6, 7, 0], [5, 6, 7, 0],
  /- 104 -/ [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 7, 0], [0, 3, 4, 5, 6, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7],
  /- 112 -/ [0, 3, 4, 5, 6, 7], [5, 6, 7, 0], [5, 6, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 6, 7, 0], [0, 3, 4, 5, 6, 7], [0, 3, 4, 5, 7],
  /- 120 -/ [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 6, 7], [5, 6, 7, 0], [5, 6, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7],
  /- 128 -/ [5, 6, 7, 0], [0, 3, 4, 5, 6, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4], [5, 6, 7, 0], [5, 6, 7, 0], [0, 3, 4, 5, 7],
  /- 136 -/ [0, 3, 4, 5, 7], [5, 6, 7, 0], [6, 5, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4], [5, 6, 7, 0], [5, 6, 7, 0],
  /- 144 -/ [5, 6, 10, 7, 0], [5, 6, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0],
  /- 152 -/ [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0, 10, 14], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7],
  /- 160 -/ [0, 3, 4, 5, 7], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7, 6],
  /- 168 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7, 6],
  /- 176 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [5, 6, 7, 0, 10, 14], [0, 3, 4, 5, 7],
  /- 184 -/ [0, 3, 4, 5, 7], [0, 3, 4, 5, 7, 6], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0],
  /- 192 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7, 6], [5, 6, 7, 0], [5, 6, 7, 0],
  /- 200 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7],
  /- 208 -/ [5, 7, 0, 3, 4, 6], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0, 10, 14], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 7, 0, 3, 4],
  /- 216 -/ [5, 7, 0, 3, 4, 6], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 7, 0], [5, 6, 10, 14, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 7, 0, 3, 4],
  /- 224 -/ [0, 3, 4], [5, 7, 0, 3, 4, 6], [5, 6, 7, 0], [5, 6, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4],
  /- 232 -/ [0, 3, 4], [5, 7, 0, 3, 4, 6], [5, 6, 7, 0], [5, 6, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 7, 0, 3, 4], [0, 3, 4, 5, 7],
  /- 240 -/ [5, 7, 0, 3, 4], [0, 3, 4, 5, 7], [5, 6, 7, 0], [5, 6, 7, 0], [0, 3, 4, 5, 7], [0, 3, 4, 5, 7], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4],
  /- 248 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4],
  /- 256 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4],
  /- 264 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4],
  /- 272 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4],
  /- 280 -/ [5, 6, 7, 0], [5, 6, 7, 0], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4],
  /- 288 -/ [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4], [5, 7, 0, 3, 4]
]

/-- The matcher certificate, decoded to head names. -/
def matcherReaders : Array (List String) :=
  decode ScaGsTables.matcherWorker matcherReadersN

/-- Paths from the two `match` rows to rows reading `B` (`available "B"` at 46 and 151). -/
def matchPaths : List (Nat × List Nat) :=
  [(84, [54, 59, 35, 41, 46]), (203, [163, 171, 179, 137, 144, 151])]

set_option maxRecDepth 100000

theorem rows_0 : rowsOk ScaGsTables.matcherWorker matcherReaders 0 100 = true := by
  decide +kernel

theorem rows_100 : rowsOk ScaGsTables.matcherWorker matcherReaders 100 100 = true := by
  decide +kernel

theorem rows_200 : rowsOk ScaGsTables.matcherWorker matcherReaders 200 94 = true := by
  decide +kernel

theorem rows_ok :
    rowsOk ScaGsTables.matcherWorker matcherReaders 0
      ScaGsTables.matcherWorker.program.code.length = true := by
  rw [ScaWorkerRegs.matcher_code_length]
  exact rowsOk_split 0 100 194 rows_0 (rowsOk_split 100 100 94 rows_100 rows_200)

theorem entries_ok : entriesOk ScaGsTables.matcherWorker matcherReadersN 6 = true := by
  decide +kernel

theorem start_ok :
    (matcherReaders.getD ScaGsTables.matcherWorker.program.start []).all
      (fun h => decide (h = "Origin" ∨ h = "Tail")) = true := by
  decide +kernel

theorem match_ok : matchOk ScaGsTables.matcherWorker matchPaths = true := by
  decide +kernel

/-- The real `liveReaders` of the matcher: below the certificate, and a post-fixpoint. -/
theorem liveReaders_spec :
    ScaWorkerRegs.Approx ScaGsTables.matcherWorker.program.code readerTransfer matcherReaders
        (liveReaders ScaGsTables.matcherWorker) ∧
      ScaWorkerRegs.PostFix ScaGsTables.matcherWorker.program.code readerTransfer
        (liveReaders ScaGsTables.matcherWorker) :=
  liveReaders_spec_of_cert rows_ok entries_ok (by decide)

/-! ## The five reader facts of the matcher -/

/-- `liveReaders` is a post-fixpoint of `readerTransfer` at every row. -/
theorem fix : ∀ (r : Nat) (row : Row), ScaGsTables.matcherWorker.program.code[r]? = some row →
    ∀ x ∈ readerTransfer row
        (successorsUnion (liveReaders ScaGsTables.matcherWorker) row.targets),
      x ∈ (liveReaders ScaGsTables.matcherWorker).getD r [] :=
  fun r row hrow _ hx => liveReaders_spec.2 r row hrow hx

/-- The reader colouring is proper on the readers live after every row. -/
theorem proper : ∀ (r : Nat) (row : Row), ScaGsTables.matcherWorker.program.code[r]? = some row →
    Proper ScaGsTables.matcherWorker
      (successorsUnion (liveReaders ScaGsTables.matcherWorker) row.targets) :=
  fun _ row hrow h hA h' hA' i hc hc' =>
    (rowOk_spec (rowOk_of_rows rows_ok hrow)).2 h
      (ScaWorkerRegs.successorsUnion_mono liveReaders_spec.1.below row.targets hA) h'
      (ScaWorkerRegs.successorsUnion_mono liveReaders_spec.1.below row.targets hA') i hc hc'

/-- Every live reader has a register, at every row index. -/
theorem colored : ∀ r : Nat, Colored ScaGsTables.matcherWorker
    ((liveReaders ScaGsTables.matcherWorker).getD r []) :=
  fun r h hh => (entries_spec entries_ok r).2 h (liveReaders_spec.1.below r hh)

/-- At the start row only `Origin` and `Tail` are live. -/
theorem startLive : ∀ h ∈ (liveReaders ScaGsTables.matcherWorker).getD
    ScaGsTables.matcherWorker.program.start [], h = "Origin" ∨ h = "Tail" := by
  intro h hh
  have hall := List.all_eq_true.mp start_ok h (liveReaders_spec.1.below _ hh)
  simpa using hall

/-- `B` is live at every `match` row. -/
theorem matchB : ∀ (r : Nat) (row : Row), ScaGsTables.matcherWorker.program.code[r]? = some row →
    ∀ h, row.event = .«match» h → "B" ∈ (liveReaders ScaGsTables.matcherWorker).getD r [] :=
  matchB_of_check liveReaders_spec.2 match_ok

end PalPeg.ScaMatcherReaders
