name = "shallot"
defaultTargets = ["Shallot", "Lens"]
testDriver = "lenstests"

[leanOptions]
autoImplicit = false

[[lean_lib]]
name = "Shallot"
roots = ["Shallot", "Audit", "Json", "MacroPeg", "Cfg", "Complexity"]

[[lean_lib]]
name = "Lens"

[[lean_exe]]
name = "extract"
root = "Lens.Main"
supportInterpreter = true

[[lean_exe]]
name = "shallot-runner"
root = "Runner"

[[lean_exe]]
name = "lenstests"
root = "LensTests"
supportInterpreter = true

[[lean_exe]]
name = "json-suite"
root = "JsonSuite"

[[lean_exe]]
name = "mpeg-runner"
root = "MPegRunner"

[[lean_exe]]
name = "counterexample-runner"
root = "CounterexampleRunner"
