package pal

/** Export instruction effects, not just the graph, from the actual PAL kernel. */
object ExportFppCode {
  def main(args: Array[String]): Unit = {
    require(args.isEmpty)
    val p = FppFinite.buildProgram("abs#")
    p.validate()
    val symbols = Vector("a", "b", "s", "#", "^", "$", "_", "0", "1")
    def symbol(s: String): Int = {
      val i = symbols.indexOf(s)
      require(i >= 0, s"unexported symbol $s")
      i
    }
    import FppFinite.Instruction.*
    println("BEGIN_LEAN_CERTIFICATE")
    println("import PalPeg.GalilFppInstruction\nimport PalPeg.GalilFppGraph")
    println("set_option autoImplicit false\nset_option maxRecDepth 100000")
    println("namespace PalPeg.GalilFppCode\nopen GalilFppInstruction")
    println("/-- Generated by pal.ExportFppCode from FppFinite.buildProgram(abs#). -/")
    println("def code : List Instruction := [")
    p.instructions.zipWithIndex.foreach { (row, q) =>
      val text = row match {
        case Halt => ".halt"
        case Emit(n) => s".emit $n"
        case Move(t, d, n) => s".move $t ${d == 1} $n"
        case Write(t, s, n) => s".write $t ${symbol(s)} $n"
        case Read(t, choices) => s".read $t " + choices.toVector.map { (s, n) => s"(${symbol(s)},$n)" }.mkString("[", ",", "]")
      }
      println("  " + text + (if (q + 1 < p.code.size) { "," } else { "" }))
    }
    println("]")
    println(s"def start : Nat := ${p.start}")
    // Longest positive A-minus-B excursion through any graph path.
    // Reject a positive cycle instead of guessing a bounded certificate.
    val potential = Array.fill(p.code.size)(0)
    var changed = true
    var iterations = 0
    while (changed && iterations <= p.code.size) {
      changed = false
      p.instructions.zipWithIndex.foreach { (row, q) =>
        val weight = row match {
          case Move(0, d, _) => d
          case Move(1, d, _) => -d
          case _ => 0
        }
        val value = (0 +: FppCost.successors(row).map(n => weight + potential(n))).max
        if (value > potential(q)) { potential(q) = value; changed = true }
      }
      iterations += 1
    }
    require(!changed, "positive A-minus-B control cycle")
    println("def potential : List Nat := " + potential.mkString("[", ",", "]"))
    println("set_option maxHeartbeats 2000000 in")
    println("theorem graph_projection : code.map projection = GalilFppGraph.graph.map (fun r => (r.1, r.2.1)) := by decide")
    println("#print axioms graph_projection\nend PalPeg.GalilFppCode")
    println("END_LEAN_CERTIFICATE")
  }
}
