package pal

/** Export the actual nine-tape marked FPP program, including preparation. */
object ExportMarkedCode {
  def main(args: Array[String]): Unit = {
    require(args.isEmpty)
    val p = FppSubroutine.buildMarkedProgram("abs")
    p.validate()
    val symbols = Vector("a", "b", "s", "#", "^", "$", "_", "0", "1")
    import FppFinite.Instruction.*
    println("BEGIN_LEAN_CERTIFICATE")
    println("import PalPeg.GalilFppWide")
    println("set_option autoImplicit false\nset_option maxRecDepth 100000")
    println("namespace PalPeg.GalilFppMarkedCode\nopen GalilFppWide")
    println("/-- Generated by pal.ExportMarkedCode from buildMarkedProgram(abs). -/")
    println("def code : List (Instruction 9) := [")
    p.instructions.zipWithIndex.foreach { (row, q) =>
      val text = row match {
        case Halt => ".halt"
        case Emit(_) => throw new IllegalStateException("marked program still emits")
        case Move(t, d, n) => s".move $t ${d == 1} $n"
        case Write(t, s, n) =>
          val symbol = symbols.indexOf(s)
          require(symbol >= 0, s"unknown symbol: $s")
          s".write $t $symbol $n"
        case Read(t, choices) =>
          s".read $t " + choices.toVector.map { (s, n) =>
            val symbol = symbols.indexOf(s)
            require(symbol >= 0, s"unknown symbol: $s")
            s"($symbol,$n)"
          }.mkString("[", ",", "]")
      }
      println("  " + text + (if (q + 1 < p.code.size) "," else ""))
    }
    println("]")
    println(s"def start : Nat := ${p.start}")
    println("end PalPeg.GalilFppMarkedCode")
    println("END_LEAN_CERTIFICATE")
  }
}
