package pal

/** Export the actual Scala-built kernel's control graph for Lean checking.
  * This proves no tape-motion ledger: it exports all branch targets, including
  * infeasible ones, and a decreasing rank between charged instructions.
  */
object ExportFppCostCertificate {
  def main(args: Array[String]): Unit = {
    require(args.isEmpty, "this certificate uses the PAL kernel alphabet abs#")
    val program = FppFinite.buildProgram("abs#")
    program.validate()
    val factor = FppCost.cutDistance(program)
    val ranks = scala.collection.mutable.Map.empty[Int, Int]
    def rank(q: Int): Int = ranks.getOrElseUpdate(q, {
      val row = program.instruction(q)
      if (FppCost.isCut(row)) { 1 }
      else { 1 + FppCost.successors(row).map(rank).max }
    })
    println("BEGIN_LEAN_CERTIFICATE")
    println("import Mathlib\n\nset_option autoImplicit false\nset_option maxRecDepth 100000")
    println("namespace PalPeg.GalilFppGraph")
    println("/-- Generated by pal.ExportFppCostCertificate from FppFinite.buildProgram(abs#). -/")
    println("def graph : List (Bool × List Nat × Nat) := [")
    program.code.indices.foreach { q =>
      val row = program.instruction(q)
      val targets = FppCost.successors(row).mkString("[", ",", "]")
      val comma = if (q + 1 < program.code.size) { "," } else { "" }
      println(s"  (${FppCost.isCut(row)}, $targets, ${rank(q)})$comma")
    }
    println("]")
    println(s"def factor : Nat := $factor")
    println("def valid : Bool := graph.all fun row =>")
    println("  decide (1 ≤ row.2.2 ∧ row.2.2 ≤ factor) &&")
    println("  row.2.1.all (fun q => decide (q < graph.length)) &&")
    println("  (if row.1 then decide (row.2.2 = 1) else")
    println("    row.2.1.all fun q => decide ((graph[q]!).2.2 < row.2.2))")
    println("set_option maxHeartbeats 2000000 in")
    println("theorem certified : valid = true := by decide")
    println("example : factor = 4 := by decide")
    println("#print axioms certified")
    println("end PalPeg.GalilFppGraph")
    println("END_LEAN_CERTIFICATE")
  }
}
