package pal

/** Export the actual twelve-tape DP program, including marked FPP and search. */
object ExportDpCode {
  def main(args: Array[String]): Unit = {
    require(args.isEmpty)
    val p = DpFinite.buildDpProgram("abs")
    p.validate()
    val symbols = Vector("a", "b", "s", "#", "^", "$", "_", "0", "1")
    def symbol(s: String): Int = {
      val i = symbols.indexOf(s)
      require(i >= 0, s"unknown symbol: $s")
      i
    }
    import FppFinite.Instruction.*
    println("BEGIN_LEAN_CERTIFICATE")
    println("import PalPeg.GalilFppWide")
    println("set_option autoImplicit false\nset_option maxRecDepth 100000")
    println("namespace PalPeg.GalilDpCode\nopen GalilFppWide")
    println("/-- Generated by pal.ExportDpCode from DpFinite.buildDpProgram(abs). -/")
    println("def code : List (Instruction 12) := [")
    p.instructions.zipWithIndex.foreach { (row, q) =>
      val text = row match {
        case Halt => ".halt"
        case Emit(_) => throw new IllegalStateException("DP program still emits")
        case Move(t, d, n) => s".move $t ${d == 1} $n"
        case Write(t, s, n) => s".write $t ${symbol(s)} $n"
        case Read(t, choices) => s".read $t " + choices.toVector.map {
          (s, n) => s"(${symbol(s)},$n)"
        }.mkString("[", ",", "]")
      }
      println("  " + text + (if (q + 1 < p.code.size) "," else ""))
    }
    val found = p.found.get
    val missed = p.instructions.zipWithIndex.collect { case (Halt, q) if q != found => q }
    require(missed.size == 1)
    println("]")
    println(s"def start : Nat := ${p.start}")
    println(s"def found : Nat := $found")
    println(s"def missed : Nat := ${missed.head}")
    println("end PalPeg.GalilDpCode")
    println("END_LEAN_CERTIFICATE")
  }
}
