import Cfg.Greibach.GNFMain
import Cfg.Greibach.Defs

/-!
# Greibach normal form, stage 4: completeness and shape

For an `EpsFree`, `UnitFree`, `RefsInRange` grammar `G`:
- `gnfG_complete`: every word in the intended language `Sem G i` of an index is generated by `gnfG G`
  (strong induction on the word length, through the left-corner decomposition `gen_decomp`);
- `gnfG_stdForm`: `gnfG G` is in Greibach's standard form;
- `gnfG_language`: `gnfG G` and `G` have the same language.
-/

namespace Shallot.Cfg

/-! ## Completeness -/

/-- The induction hypothesis: all shorter words of every index are generated. -/
def ShorterOk (G : CFGrammar) (w : List Char) : Prop :=
  ∀ j x, x.length < w.length → j < gnfBound G.rules.length → Sem G j x → Gen (gnfG G) j x

/-- An old nonterminal is an index of the new grammar. -/
theorem lt_gnfBound_of_lt {n j : Nat} (h : j < n) : j < gnfBound n := by unfold gnfBound; omega

/-- `⟨A/C⟩` is an index of the new grammar. -/
theorem tIdx_lt_gnfBound {n A C : Nat} (hA : A < n) (hC : C < n) : tIdx n A C < gnfBound n := by
  have := (tIdx_bounds hA hC).2
  unfold gnfBound; omega

/-- The terminal nonterminals generate their terminal. -/
theorem gen_termIdx (G : CFGrammar) (c : Char) : Gen (gnfG G) (termIdx G.rules.length c) [c] := by
  have halts := altsAt_gnfG G (termIdx G.rules.length c)
  rw [if_pos (termIdx_bounds _ c).2, gnfAlts_termIdx] at halts
  exact gen_of_rule halts List.mem_cons_self ⟨[], rfl, rfl⟩

/-- An old nonterminal's words in the new grammar, from its sides `eAlts`. -/
theorem gen_gnfG_lt {G : CFGrammar} {E : Nat} (hE : E < G.rules.length) {rhs : Rhs} {w : List Char}
    (hm : rhs ∈ eAlts G E) (hw : SemRhs (Gen (gnfG G)) rhs w) : Gen (gnfG G) E w := by
  have halts := altsAt_gnfG G E
  rw [if_pos (lt_gnfBound_of_lt hE), gnfAlts_lt hE] at halts
  exact gen_of_rule halts hm hw

/-- `⟦β⟧` generates in the new grammar what `β` generates in `G`, given shorter-or-equal pieces. -/
theorem semRhs_tr_complete {G : CFGrammar} :
    ∀ (β : List Sym), (∀ j, Sym.nt j ∈ β → j < G.rules.length) → ∀ (u : List Char),
      (∀ j x, x.length ≤ u.length → j < G.rules.length → Gen G j x → Gen (gnfG G) j x) →
      SemRhs (Gen G) β u → SemRhs (Gen (gnfG G)) (tr G.rules.length β) u
  | [], _, _, _, h => h
  | .t c :: β, hβ, _, hIH, h => by
      obtain ⟨y, rfl, hy⟩ := h
      refine ⟨[c], y, rfl, gen_termIdx G c, semRhs_tr_complete β (fun j hj => hβ j (List.mem_cons_of_mem _ hj)) y
        (fun j x hx => hIH j x (by simp only [List.length_cons]; omega)) hy⟩
  | .nt j :: β, hβ, _, hIH, h => by
      obtain ⟨x, y, rfl, hx, hy⟩ := h
      refine ⟨x, y, rfl, hIH j x (by simp only [List.length_append]; omega) (hβ j List.mem_cons_self) hx,
        semRhs_tr_complete β (fun k hk => hβ k (List.mem_cons_of_mem _ hk)) y
          (fun k z hz => hIH k z (by simp only [List.length_append]; omega)) hy⟩

/-- Shorter old-nonterminal words, from the induction hypothesis. -/
theorem shorter_gen {G : CFGrammar} {w : List Char} (ih : ShorterOk G w) {u : List Char}
    (hu : u.length < w.length) : ∀ j x, x.length ≤ u.length → j < G.rules.length → Gen G j x →
      Gen (gnfG G) j x :=
  fun j x hx hj hg => ih j x (by omega) (lt_gnfBound_of_lt hj) ((sem_lt hj x).mpr hg)

/-- Shorter `⟨A/C⟩` words, from the induction hypothesis. -/
theorem shorter_tIdx {G : CFGrammar} {w : List Char} (ih : ShorterOk G w) {A C : Nat}
    (hA : A < G.rules.length) (hC : C < G.rules.length) {v : List Char} (hv : v.length < w.length)
    (hlc : LeftCorner G A C v) (hne : v ≠ []) : Gen (gnfG G) (tIdx G.rules.length A C) v :=
  ih _ v hv (tIdx_lt_gnfBound hA hC) ((sem_tIdx hA hC v).mpr ⟨hlc, hne⟩)

/-- **Completeness of `eAlts`**: every word of an old nonterminal is a word of one of its new sides. -/
theorem eAlts_complete {G : CFGrammar} (hε : EpsFree G) (hU : UnitFree G) (hR : RefsInRange G)
    {E : Nat} (hE : E < G.rules.length) {w : List Char} (hw : Gen G E w) (ih : ShorterOk G w) :
    ∃ rhs ∈ eAlts G E, SemRhs (Gen (gnfG G)) rhs w := by
  obtain ⟨F, a, β, u, v, hF, hu, hv, rfl⟩ := gen_decomp hε hw
  have hFn := lt_of_mem_altsOf hF
  have hβ : ∀ j, Sym.nt j ∈ β → j < G.rules.length :=
    fun j hj => refs_of_mem_altsOf hR hF j (List.mem_cons_of_mem _ hj)
  have hlen : (u ++ v).length < (a :: (u ++ v)).length := by simp only [List.length_cons]; omega
  have htr := semRhs_tr_complete β hβ u
    (shorter_gen ih (by simp only [List.length_append, List.length_cons] at hlen ⊢; omega)) hu
  have hmemE : ∀ rhs, rhs ∈ eRule G.rules.length E F (.t a :: β) → rhs ∈ eAlts G E :=
    fun rhs h => mem_eAlts.mpr ⟨hE, F, _, hFn, hF, h⟩
  by_cases hv0 : v = []
  · subst hv0
    have hFE := leftCorner_nil hε hU hv rfl
    subst hFE
    refine ⟨.t a :: tr G.rules.length β, hmemE _ ?_, u, by rw [List.append_nil], htr⟩
    simp only [eRule, ↓reduceIte, List.mem_append, List.mem_singleton, true_or]
  · refine ⟨.t a :: (tr G.rules.length β ++ [.nt (tIdx G.rules.length E F)]), hmemE _ ?_, u ++ v, rfl,
      (semRhs_append _ _ _ _).mpr ⟨u, v, rfl, htr, (semRhs_single_nt _ _ _).mpr ?_⟩⟩
    · simp only [eRule, List.mem_append, List.mem_singleton, or_true]
    · exact shorter_tIdx ih hE hFn (by simp only [List.length_append, List.length_cons]; omega) hv hv0

/-- A side of a symbol yields its words in the new grammar, with a nonempty word. -/
theorem heads_complete {G : CFGrammar} (hε : EpsFree G) (hU : UnitFree G) (hR : RefsInRange G)
    {w : List Char} (ih : ShorterOk G w) {Y : Sym} (hY : ∀ j, Y = .nt j → j < G.rules.length)
    {γ : List Sym} {u : List Char} (hu : SemRhs (Gen G) (Y :: γ) u) (hlen : u.length ≤ w.length) :
    ∃ h x y, h ∈ heads G Y ∧ u = x ++ y ∧ x ≠ [] ∧ SemRhs (Gen (gnfG G)) h x ∧ SemRhs (Gen G) γ y := by
  cases Y with
  | t c =>
      obtain ⟨y, rfl, hy⟩ := hu
      exact ⟨[.t c], [c], y, List.mem_singleton_self _, rfl, List.cons_ne_nil _ _, ⟨[], rfl, rfl⟩, hy⟩
  | nt E =>
      obtain ⟨x, y, rfl, hx, hy⟩ := hu
      have hE := hY E rfl
      obtain ⟨h, hh, hxh⟩ := eAlts_complete hε hU hR hE hx
        (fun j z hz => ih j z (by simp only [List.length_append] at hlen; omega))
      exact ⟨h, x, y, hh, rfl, gen_ne_nil hε hx, hxh, hy⟩

/-- **Completeness of `tAlts`**: every nonempty left-corner word is a word of one of the new sides. -/
theorem tAlts_complete {G : CFGrammar} (hε : EpsFree G) (hU : UnitFree G) (hR : RefsInRange G)
    {A C : Nat} (hA : A < G.rules.length) {w : List Char} (hw : LeftCorner G A C w) (hne : w ≠ [])
    (ih : ShorterOk G w) : ∃ rhs ∈ tAlts G A C, SemRhs (Gen (gnfG G)) rhs w := by
  cases hw with
  | refl => exact absurd rfl hne
  | @step _ D α u v hr hu hv =>
      have hDn := lt_of_mem_altsOf hr
      obtain ⟨a, ha, hra⟩ := mem_rules_of_mem_altsOf hr
      match α, hu, hr, hra with
      | [], _, _, hra => exact absurd (hU a ha _ hra) (by simp [isUnitRhs])
      | Y :: γ, hu, hr, _ =>
          have hrefs := refs_of_mem_altsOf hR hr
          obtain ⟨h, x, y, hh, rfl, hx0, hxh, hy⟩ := heads_complete hε hU hR ih
            (fun j hj => hrefs j (by rw [hj]; exact List.mem_cons_of_mem _ List.mem_cons_self)) hu
            (by simp only [List.length_append]; omega)
          have hxl : x.length ≠ 0 := fun h0 => hx0 (List.eq_nil_of_length_eq_zero h0)
          have htr := semRhs_tr_complete γ
            (fun j hj => hrefs j (List.mem_cons_of_mem _ (List.mem_cons_of_mem _ hj))) y
            (shorter_gen ih (u := y) (by simp only [List.length_append]; omega)) hy
          have hmemT : ∀ t ∈ tails G.rules.length A D, h ++ tr G.rules.length γ ++ t ∈ tAlts G A C :=
            fun t ht => mem_tAlts.mpr ⟨D, _, hDn, hr, mem_tRule.mpr ⟨Y, γ, h, t, rfl, hh, ht, rfl⟩⟩
          by_cases hv0 : v = []
          · subst hv0
            have hDA := leftCorner_nil hε hU hv rfl
            refine ⟨h ++ tr G.rules.length γ ++ [], hmemT _ (mem_tails.mpr (Or.inl ⟨hDA, rfl⟩)), ?_⟩
            refine (semRhs_append _ _ _ _).mpr ⟨x ++ y, [], by rw [List.append_nil], ?_, rfl⟩
            exact (semRhs_append _ _ _ _).mpr ⟨x, y, rfl, hxh, htr⟩
          · refine ⟨h ++ tr G.rules.length γ ++ [.nt (tIdx G.rules.length A D)],
              hmemT _ (mem_tails.mpr (Or.inr rfl)), ?_⟩
            refine (semRhs_append _ _ _ _).mpr ⟨x ++ y, v, rfl, ?_, (semRhs_single_nt _ _ _).mpr ?_⟩
            · exact (semRhs_append _ _ _ _).mpr ⟨x, y, rfl, hxh, htr⟩
            · exact shorter_tIdx ih hA hDn (by simp only [List.length_append]; omega) hv hv0

/-- **Completeness**: every word in the intended language of an index is generated by `gnfG G`. -/
theorem gnfG_complete {G : CFGrammar} (hε : EpsFree G) (hU : UnitFree G) (hR : RefsInRange G) :
    ∀ i w, i < gnfBound G.rules.length → Sem G i w → Gen (gnfG G) i w := by
  refine len_induction (fun i w => i < gnfBound G.rules.length → Sem G i w → Gen (gnfG G) i w) ?_
  intro i w ih hi hs
  have halts := altsAt_gnfG G i
  rw [if_pos hi] at halts
  by_cases h₁ : i < G.rules.length
  · rw [sem_lt h₁] at hs
    obtain ⟨rhs, hm, hr⟩ := eAlts_complete hε hU hR h₁ hs ih
    exact gen_gnfG_lt h₁ hm hr
  · by_cases h₂ : i < G.rules.length + G.rules.length * G.rules.length
    · obtain ⟨hA, hC, hi'⟩ := tIdx_encode (Nat.le_of_not_lt h₁) h₂
      rw [hi'] at hs halts ⊢
      rw [sem_tIdx hA hC] at hs
      rw [gnfAlts_tIdx hA hC] at halts
      obtain ⟨rhs, hm, hr⟩ := tAlts_complete hε hU hR hA hs.1 hs.2 ih
      exact gen_of_rule halts hm hr
    · by_cases h₃ : i = G.rules.length + G.rules.length * G.rules.length
      · have hi' : i = sIdx G.rules.length := h₃
        rw [hi'] at hs halts ⊢
        rw [sem_sIdx] at hs
        rw [gnfAlts_sIdx] at halts
        obtain ⟨rhs, hm, hr⟩ := eAlts_complete hε hU hR (gen_lt hs) hs ih
        exact gen_of_rule halts hm hr
      · simp only [Sem, if_neg h₁, if_neg h₂, if_neg h₃] at hs
        simp only [gnfAlts, if_neg h₁, if_neg h₂, if_neg h₃] at halts
        subst hs
        exact gen_of_rule halts List.mem_cons_self ⟨[], rfl, rfl⟩

/-- **Stage 4 keeps the language**: the fresh start of `gnfG G` generates the language of `G`. -/
theorem gnfG_language {G : CFGrammar} (hε : EpsFree G) (hU : UnitFree G) (hR : RefsInRange G)
    (w : List Char) : (gnfG G).language w ↔ G.language w := by
  show Gen (gnfG G) (sIdx G.rules.length) w ↔ Gen G G.start w
  constructor
  · intro h; exact (sem_sIdx G w).mp (gnfG_sound hε hR h)
  · intro h
    have hb : sIdx G.rules.length < gnfBound G.rules.length := by unfold sIdx gnfBound; omega
    exact gnfG_complete hε hU hR _ w hb ((sem_sIdx G w).mpr h)

/-! ## Shape -/

/-- A Greibach side whose nonterminals avoid the fresh start. -/
def GoodRhs (n : Nat) (rhs : Rhs) : Prop :=
  ∃ a rest, rhs = .t a :: rest ∧ ∀ s ∈ rest, ∃ j, s = .nt j ∧ j ≠ sIdx n

/-- `⟦β⟧` consists of nonterminals other than the fresh start. -/
theorem tr_good {n : Nat} {β : List Sym} (hβ : ∀ j, Sym.nt j ∈ β → j < n) :
    ∀ s ∈ tr n β, ∃ j, s = .nt j ∧ j ≠ sIdx n := by
  intro s hs
  simp only [tr, List.mem_map] at hs
  obtain ⟨s', hs', rfl⟩ := hs
  cases s' with
  | t c => exact ⟨termIdx n c, rfl, Nat.ne_of_gt (termIdx_bounds n c).1⟩
  | nt j =>
      have := hβ j hs'
      exact ⟨j, rfl, by unfold sIdx; omega⟩

/-- The sides of `eAlts` are good. -/
theorem eAlts_good {G : CFGrammar} (hR : RefsInRange G) {E : Nat} {rhs : Rhs} (hm : rhs ∈ eAlts G E) :
    GoodRhs G.rules.length rhs := by
  obtain ⟨hE, F, r, hF, hr, hrule⟩ := mem_eAlts.mp hm
  obtain ⟨a, β, rfl, hcase⟩ := mem_eRule hrule
  have hβ : ∀ j, Sym.nt j ∈ β → j < G.rules.length :=
    fun j hj => refs_of_mem_altsOf hR hr j (List.mem_cons_of_mem _ hj)
  rcases hcase with ⟨_, rfl⟩ | rfl
  · exact ⟨a, _, rfl, tr_good hβ⟩
  · refine ⟨a, _, rfl, fun s hs => ?_⟩
    rcases List.mem_append.mp hs with hs | hs
    · exact tr_good hβ s hs
    · rw [List.mem_singleton] at hs
      subst hs
      have := (tIdx_bounds hE hF).2
      exact ⟨_, rfl, by unfold sIdx; omega⟩

/-- The sides of `tAlts` are good. -/
theorem tAlts_good {G : CFGrammar} (hR : RefsInRange G) {A C : Nat} (hA : A < G.rules.length)
    {rhs : Rhs} (hm : rhs ∈ tAlts G A C) : GoodRhs G.rules.length rhs := by
  obtain ⟨D, r, hD, hr, hrule⟩ := mem_tAlts.mp hm
  obtain ⟨Y, γ, h, t, rfl, hh, ht, rfl⟩ := mem_tRule.mp hrule
  have hγ : ∀ j, Sym.nt j ∈ γ → j < G.rules.length :=
    fun j hj => refs_of_mem_altsOf hR hr j (List.mem_cons_of_mem _ (List.mem_cons_of_mem _ hj))
  have hgh : GoodRhs G.rules.length h := by
    cases Y with
    | t c =>
        simp only [heads, List.mem_singleton] at hh; subst hh
        exact ⟨c, [], rfl, fun s hs => absurd hs List.not_mem_nil⟩
    | nt E => exact eAlts_good hR hh
  obtain ⟨a, rest, rfl, hrest⟩ := hgh
  refine ⟨a, rest ++ tr G.rules.length γ ++ t, by simp only [List.cons_append], fun s hs => ?_⟩
  rcases List.mem_append.mp hs with hs | hs
  · rcases List.mem_append.mp hs with hs | hs
    · exact hrest s hs
    · exact tr_good hγ s hs
  · rcases mem_tails.mp ht with ⟨_, rfl⟩ | rfl
    · exact absurd hs List.not_mem_nil
    · rw [List.mem_singleton] at hs
      subst hs
      have := (tIdx_bounds hA hD).2
      exact ⟨_, rfl, by unfold sIdx; omega⟩

/-- Every side of `gnfG G` is good. -/
theorem gnfAlts_good {G : CFGrammar} (hR : RefsInRange G) (i : Nat) {rhs : Rhs} (hm : rhs ∈ gnfAlts G i) :
    GoodRhs G.rules.length rhs := by
  by_cases h₁ : i < G.rules.length
  · rw [gnfAlts_lt h₁] at hm; exact eAlts_good hR hm
  · by_cases h₂ : i < G.rules.length + G.rules.length * G.rules.length
    · obtain ⟨hA, hC, hi⟩ := tIdx_encode (Nat.le_of_not_lt h₁) h₂
      rw [hi, gnfAlts_tIdx hA hC] at hm
      exact tAlts_good hR hA hm
    · by_cases h₃ : i = G.rules.length + G.rules.length * G.rules.length
      · have hi : i = sIdx G.rules.length := h₃
        rw [hi, gnfAlts_sIdx] at hm
        exact eAlts_good hR hm
      · simp only [gnfAlts, if_neg h₁, if_neg h₂, if_neg h₃, List.mem_singleton] at hm
        subst hm
        exact ⟨_, [], rfl, fun s hs => absurd hs List.not_mem_nil⟩

/-- **Stage 4 reaches Greibach's standard form.** -/
theorem gnfG_stdForm {G : CFGrammar} (hR : RefsInRange G) : StdForm (gnfG G) := by
  intro alts halts rhs hrhs
  simp only [gnfG, List.mem_map] at halts
  obtain ⟨i, _, rfl⟩ := halts
  obtain ⟨a, rest, rfl, hrest⟩ := gnfAlts_good hR i hrhs
  refine ⟨⟨a, rest, rfl, fun s hs => ?_⟩, ?_⟩
  · obtain ⟨j, hj, _⟩ := hrest s hs; exact ⟨j, hj⟩
  · intro hmem
    rcases List.mem_cons.mp hmem with h | h
    · exact Sym.noConfusion h
    · obtain ⟨j, hj, hne⟩ := hrest _ h
      cases hj
      exact hne rfl

end Shallot.Cfg
